### ISSUE TITLE
Support 'empty' *Request objects

### ISSUE THREAD

**Issue by carstenlenz** [mcohen01/amazonica#101]
The Opsworks package has a Client that always take a *Request object but which can be empty (no methods called / parameters set).

Example is the `AWSOpsWorksClient.describeStacks(DescribeStacksRequest)` method that always takes a DescribeStacksRequest object which can be empty (meaning the method `setStackIds()` is never called which will then return all stacks) 

`(amazonica.aws.opsworks/describe-stacks)` does not work as there is no no-arg version of that method but I could not get amazonica to create an `DescribeStacksRequest` without any parameters set.

If I try `(amazonica.aws.opsworks/describe-stacks :stack-ids [])` I get a `ValidationException` to either provide no arguments or one or more stack IDs.

Am I missing something?

**Comment by mcohen01** [comment]
Interesting. I think this is the first case of ever having to pass an empty map a la `(amazonica.aws.opsworks/describe-stacks {})`. Fix version is 0.3.7

**Comment by carstenlenz** [comment]
Cool. Thank you.
