### ISSUE TITLE
Can't use a credentials provider

### ISSUE THREAD

**Issue by ddossot** [mcohen01/amazonica#103]
I'm trying to use an `AWSCredentialsProvider` with Amazonica.

At first I tried with `with-credential` but it's not possible that way. So, following this from the README:

> Additionally, all of the functions may take as their first argument an optional map of credentials:
> ...
> Or rather than a Clojure map, the argument may be an actual instance or subclass of either AWSCredentialsProvider or AWSCredentials.

I tried the following:

    (sqs/list-queues cred-pro "my-queue")

but I receive:

    ClassCastException com.amazonaws.auth.DefaultAWSCredentialsProviderChain cannot be cast to clojure.lang.IPersistentMap  clojure.lang.RT.dissoc (RT.java:758)

Clearly, I misunderstood the documentation.

So how does one use an `AWSCredentialsProvider` with Amazonica?

**Comment by stevemkim** [comment]
I would also like to know the answer to this question. Is the documentation accurate in this respect? I looked at the `args-from` helper function `amazonica.core` and it seems strange to me.

**Comment by mcohen01** [comment]
Sorry about that. Not sure when this broke.

**Comment by ddossot** [comment]
Cool, no worries, thanks for the quick fix!

What would be the correct way to use a credential provider and specify the
endpoint/region?

**Comment by mcohen01** [comment]
Looks like it's just `:cred` key:

```(sqs/list-queues {:cred (DefaultAWSCredentialsProviderChain.)
                   :endpoint "us-west-2"} 
                  "my-queue")
```

**Comment by ddossot** [comment]
Yes, it works great with `:cred` :dancers: Thank you so much.
