### ISSUE TITLE
OpsWorks: describe-stacks without parameters fails

### ISSUE THREAD

**Issue by githuesch** [mcohen01/amazonica#105]
When I work with AWS OpsWorks, the first call I make is usually `describe-stacks` with parameters, just to see what's already there. I can make that call with the Java SDK, but not with amazonica. With the following patch I got it to work, but I wasn't sure whether or not that's a good way to fix the issue, hence no pull request. If getting rid of the forms I'm commenting out does make sense, really removing them instead of merely commenting them out would of course be preferable, and in that case I'd be happy to create a pull request, along with a proper test.

```
diff --git src/amazonica/core.clj src/amazonica/core.clj
index bd6cd63..26611a7 100644
--- src/amazonica/core.clj
+++ src/amazonica/core.clj
@@ -637,7 +637,7 @@
 (defn- use-aws-request-bean?
   [method args]
   (let [types (.getParameterTypes method)]
-    (and (< 1 (count args))
+    (and #_ (< 1 (count args))
          (< 0 (count types))
          (and
             (or (and
@@ -646,7 +646,7 @@
                 (and
                   (odd? (count args))
                   (= java.io.File (last types)))) ; s3 getObject() support
-            (some keyword? args))
+            #_ (some keyword? args))
          (or (aws-package? (first types))
              (and (aws-package? (last types))
                   (not (< (count types) (count args))))))))
 ```

**Comment by mcohen01** [comment]
What happens when you call `(ops/describe-stacks {})`?

**Comment by githuesch** [comment]
It seems like this was broken until 0.3.4. I tested again with 0.3.10 and it works fine when passing `{}`.
My bad for not testing with the latest version before cutting the issue, sorry.
