### ISSUE TITLE
Silently failing CloudWatch `put-metric-data` command

### ISSUE THREAD

**Issue by kyptin** [mcohen01/amazonica#107]
When I run this code, `cloudwatch/put-metric-data` returns `nil` but the metric never appears in CloudWatch:

```clojure
(require '[amazonica.aws.cloudwatch :as cloudwatch])
(defn report-to-cloudwatch []
  (cloudwatch/put-metric-data
    :namespace "test_namespace"
    :metric-data [{:metric-name "test_metric"
                   :unit "Count"
                   :value 1.0}]))
```

Whereas if I run this code that shells out to `aws cloudwatch`, it works:

```clojure
(require '[clojure.java.shell :as shell])
(defn report-to-cloudwatch []
  (shell/sh "aws" "cloudwatch" "put-metric-data"
            "--metric-name" "TestMetric"
            "--namespace" "TestNamespace"
            "--region" "us-west-1"
            "--value" "1.0"
            :env {"IAM_ROLE" (environ/env :iam-role)}))
```

Of course, there are some differences here other than shell vs. Amazonica. Perhaps Amazonica needs an IAM_ROLE as well? I'm not sure.

The problem is, I can't tell what's wrong with the Amazonica example because it throws no exception, returns nothing helpful, and I can find no working examples. So I guess I'm reporting either a broken `put-metric-data` function, a unhelpfully caught exception, missing documentation—or else just user error. :-)

**Comment by mcohen01** [comment]
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/AmazonCloudWatchClient.html#putMetricData(com.amazonaws.services.cloudwatch.model.PutMetricDataRequest)

**Comment by kyptin** [comment]
Thanks, yeah, I did see that, but I had to do some trial-and-error to figure out that e.g. the `MetricDatum` could be specified with a map in Amazonica. (Part of my difficulty here may be that I've never really messed with or understood Java beans before. If it's a basic RTFM issue, sorry, and thanks for your patience.)

I like your avatar, dude.

**Comment by mcohen01** [comment]
Sorry for being short, on the phone on the train atm. Yeah, it often helps to have ajava background with clojure, especially with libraries like this one! Shomer shabbas.

**Comment by kyptin** [comment]
Yeah, makes sense that a deeper Java background would be useful here.

Sorry, I'm still confused. Would you mind elaborating where I went wrong, or what the right way to do this in Amazonica would be? Thanks!

**Comment by mcohen01** [comment]
You have it right! You should see your metric and the value in the aws console.

**Comment by mcohen01** [comment]
That's what I meant with the javadoc link, where it says it may take a few minutes to show up

**Comment by kyptin** [comment]
Oh OK. Nice to know I got it right after all. :-) But I waited for more than the allotted 15 minutes, and it never did show up, in either the console or the output of `aws cloudwatch list-metrics`. Whereas with the shell-based version, it showed up within a couple of minutes.

Maybe I needed an `IAM_ROLE` or AWS region set or something. But I'm thinking I should have gotten an exception if that were the case.

**Comment by mcohen01** [comment]
Ahh, I just re-read your initial post. Default region with amazonica is going to be us-east-1. Your metric is probably there. With the shell command you specified us-west-1. You can specify the region with:

```clj
(cloudwatch/put-metric-data
    {:endpoint "us-west-1"}
    :namespace "test_namespace"
    :metric-data [{:metric-name "test_metric"
                   :unit "Count"
                   :value 1.0}])
```

**Comment by kyptin** [comment]
Ah, you know, I bet that's exactly what's going on. Good catch! I'll try this out soon, probably tomorrow, and let you know for sure whether that was it. Thanks a lot!

**Comment by kyptin** [comment]
Yep, that was exactly it! Thanks a lot!
