### ISSUE TITLE
Aborting upload

### ISSUE THREAD

**Issue by bilus** [mcohen01/amazonica#113]
Trying to find my way around the source, I wasn't able to figure it out: how do I abort an upload in progress (initiated using amazonica.aws.s3transfer/upload). Thanks!

**Comment by mcohen01** [comment]
Looks like these methods were added onto Upload at some point. Now you can do something like

```clj
(let [upload (upload bucket
                     filename
                     (java.io.File. filename))]
  (if some-condition
      ((:abort upload))))
```
