### ISSUE TITLE
lein test fails with compile-time exception due to import conflicts

### ISSUE THREAD

**Issue by jmglov** [mcohen01/amazonica#115]
`amazonica.test.core` imports the `set-endpoint` var (at least) twice:

```
: jmglov@alhana; lein test
Exception in thread "main" java.lang.IllegalStateException: set-endpoint already refers to: #'amazonica.aws.datapipeline/set-endpoint in namespace: amazonica.test.core, compiling:(amazonica/test/core.clj:1:1)
```

I'm not really sure where the second `set-endpoint` is coming from, as it is being interned from a Java client by `amazonica.core/set-client`. Hopefully someone can cast some light on this; otherwise I probably need to go through the Amazon Java SDK's Javadoc, package by package, until I find all the clients with a `setEndpoint()` method. :(

**Comment by mcohen01** [comment]
Thanks Josh. Sorry about that.
