### ISSUE TITLE
How to pass parameters to cloudformation/create-stack?

### ISSUE THREAD

**Issue by d11wtq** [mcohen01/amazonica#117]
I'm passing parameters to `(create-stack)` like so:

``` clojure
(cloudformation/create-stack :stack-name "name"
                                              :template-body "{ ... JSON ... }"
                                              :parameters [{:parameter-key "dockerImage", :parameter-value "example"}])
```

But the client always complains that "dockerImage" parameter must be provided. What's the expected input format? In most clients, the payload key is "Parameters" and the data structure is a list of JSON Objects `{"ParameterKey": "dockerImage", "ParameterValue": "example"}`.

**Comment by mcohen01** [comment]
```clj
(create-stack :stack-name "name"
              :template-body "[]"
              :parameters [{:parameter-key "dockerImage", 
                            :parameter-value "example"}])
```

gives me "Template format error: unsupported type or structure." i.e. AWS server side validation error, from the empty template, but no client error

**Comment by d11wtq** [comment]
You need a template with some required parameters for it to happen, but you have pointed me in the right direction. The `:parameter-key` value in my actual code is the keyword `:dockerImage` rather than a string and that seems to be tripping it up.
