### ISSUE TITLE
How to set S3 path style?

### ISSUE THREAD

**Issue by Integralist** [mcohen01/amazonica#119]
Hi,

I'm a Ruby dev moving over to Clojure and I'm having trouble understanding how to translate the following Java call into Clojure based on the conventions used in Amazonica.

```java
AmazonS3 client = new AmazonS3Client(credentials);
client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
```

The code I have at the moment is:

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3]])
  (:require [amazonica.core :refer [ex->map]]))

(def credentials {:access-key "development_access"
                  :secret-key "development_secret"
                  :endpoint "s3.spurious.localhost:49154"
                  :client-config {:protocol "http"}})

(try
  (amazonica.aws.s3/set-s3client-options {:path-style-access true})
  (create-bucket credentials "testing")
  (catch Exception e
    (clojure.pprint/write (ex->map e))))
```

But I'm getting the following error:

```
com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: testing.s3.spurious.localhost
java.net.UnknownHostException: testing.s3.spurious.localhost
```

This doesn't look to be correct as it's prefixing the bucket name (`testing`) onto the hostname. Where as I need the SDK to talk to our local (fake) S3 service (`s3.spurious.localhost:49154`) using path style.

e.g. like `http://s3.spurious.localhost:49154/testing` 

I think it's because I'm not translating the Java code correctly...

```clj
(amazonica.aws.s3/set-s3client-options {:path-style-access true})
```

...this is passing a map to `set-s3client-options` rather than what it should be, which is passing the result of calling `withPathStyleAccess(true)` on a new instance of `S3ClientOptions`. But I don't know how to do that here?

Any help you can give me would be greatly appreciated.

**Comment by mcohen01** [comment]
Sorry, in a handful of cases the camel case conversion can be ambiguous. In general, it just replaces any capital letters in the Java method name with lowercase prepended with a dash, and that becomes the Clojure function name. So in this case the function call would be:
```clj
(set-s3client-options :path-style-access true)
```

**Comment by jonoflayham** [comment]
I've not used the API, but if set-s3client-options really does take the same thing as the Java API, then try

(.withPathStyleAccess (com.amazonaws.services.s3.S3ClientOptions.))

The .withPathStyleAccess is a method treated as a Clojure function which is evaluated in the context of what immediately follows it - which is in turn a function call which creates a new instance of S3ClientOptions.    You might find http://clojure-doc.org/articles/language/interop.html useful.

**Comment by mcohen01** [comment]
I'm pretty sure there's nothing wrong with the S3 client options related calls. `withPathStyleAccess` vs `setPathStyleAccess` makes no difference. with* is just the "fluent api" idiom that returns this rather than set* returning void. 

Can you try calling `(create-bucket credentials :bucket-name "testing")`? There are a handful of cases in the AWS api (S3 in particular) where the api is not so uniform, overloaded methods with several implementations, that amazonica has always had a bit of trouble dealing with. In these cases, if there's a Java method available that takes a single AWS-specific *Request object, rather than multiple java.lang.* objects (i.e. strings, ints, etc), it usually works to use the more explicit, albeit more verbose, Java method by passing a Clojure map (or key value args).

**Comment by Integralist** [comment]
Hi @mcohen01 @jonoflayham thanks for the feedback. 

Just to be clear: I *need* to set the S3 "path style access" to `true`, otherwise no other function calls will work. 

The reason why this won't work without that property set to `true` is because my fake S3 service is set-up to use "path style access". 

So for example, assuming we had a bucket created called `foo`; then the endpoint `http://s3.spurious.localhost:49154/foo` would successfully access the bucket `foo`; but `http://foo.s3.spurious.localhost:49154/` would not work.

So my question fundamentally comes down to "how do I set 'path style' to true?" (in the hope that's all that is required to get my example working)

As mentioned before, Java seem to do this like so:

```java
AmazonS3 client = new AmazonS3Client(credentials);
client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));
```

I've tried three different variations:

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3])
  (:require [amazonica.core :refer [ex->map]]))

(def credentials {:access-key "development_access"
                  :secret-key "development_secret"
                  :endpoint "s3.spurious.localhost:49154"
                  :client-config {:protocol "http"}})

(try
  ; (.withPathStyleAccess (com.amazonaws.services.s3.S3ClientOptions.))
  ; (. (com.amazonaws.services.s3.S3ClientOptions.) withPathStyleAccess)
  (. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true)
  (create-bucket credentials "testing")
  (catch Exception e
    (clojure.pprint/write (ex->map e))))
```

But in all three examples I get the following error...

```
CompilerException java.lang.IllegalArgumentException: No matching field found: getErrorCode for class com.amazonaws.AmazonClientException
```

If I look in the Lein REPL I can see a *very* long error output, but at the top of it is...

```
com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: testing.s3.spurious.localhost: unknown error
java.net.UnknownHostException: testing.s3.spurious.localhost: unknown error
```

...which suggests (`testing.s3.spurious.localhost`) that the long form `setPathStyleAccess` method call (from my third example above) hasn't actually been applied.

AmazonS3 client = new AmazonS3Client(credentials);
client.setS3ClientOptions(new S3ClientOptions().withPathStyleAccess(true));

If we look again at the Java example, we can see that the result of calling `withPathStyleAccess` (on `S3ClientOptions`) is passed into `setS3ClientOptions`. So I tried this and got a different error...

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3])
  (:require [amazonica.core :refer [ex->map]]))

(def credentials {:access-key "development_access"
                  :secret-key "development_secret"
                  :endpoint "s3.spurious.localhost:49154"
                  :client-config {:protocol "http"}})

(try
  (amazonica.aws.s3/set-s3client-options 
    (. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true))
  (create-bucket credentials "testing")
  (catch Exception e
    (clojure.pprint/write (ex->map e))))
```

...after executing the above example I get the same error as before, but if I execute only the line `(amazonica.aws.s3/set-s3client-options (. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true))`, then I get the following error...

```
Could not determine best method to invoke for set-s3client-options using arguments (nil)
```

Any ideas on what I might be missing?

**Comment by jonoflayham** [comment]
There's an example of setting client options [here](https://github.com/mcohen01/amazonica/blob/master/test/amazonica/test/s3.clj#L131) which suggests that your credentials map could maybe have an additional key-value pair like ``:path-style-access true`` (or some variant of that) to do this.

**Comment by Integralist** [comment]
Hi @jonoflayham 

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3]))

(def credentials {:access-key "development_access"
                  :secret-key "development_secret"
                  :endpoint "s3.spurious.localhost:49154"
                  :client-config {:protocol "http" :path-style-access true}})

(create-bucket credentials "testing")
```

...results in the following error...

```
CompilerException com.amazonaws.AmazonClientException: Unable to execute HTTP request: testing.s3.spurious.localhost, c
ompiling:(spurious_aws_sdk_helper/core.clj:7:79)
```

...this is the exact problem I described earlier (i.e. it seems to be trying to make a HTTP request - I assume a `POST` request - using `http://testing.s3.spurious.localhost:49154/` instead of what I'm expecting it to use `http://s3.spurious.localhost:49154/testing`)

/cc @mcohen01

**Comment by Integralist** [comment]
@jonoflayham I've looked back at the Java docs and it looks like you don't specify path style access as part of the [client config](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html) credentials passed to the [AmazonS3Client](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html) -> as you've suggested doing in your example.

If you look at the [ClientConfiguration](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/ClientConfiguration.html) object that is passed to the [AmazonS3Client](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html) you'll see it doesn't have a `setS3ClientOptions` method. That method exists only on the AmazonS3Client -> as you can see here: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#setS3ClientOptions(com.amazonaws.services.s3.S3ClientOptions)

The `setS3ClientOptions` method takes in an [S3ClientOptions](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/S3ClientOptions.html) object that has a `setPathStyleAccess` method.

You'll see this is why I was attempting the following code:

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3]))

(def credentials {:access-key "development_access"
                  :secret-key "development_secret"
                  :endpoint "s3.spurious.localhost:49154"
                  :client-config {:protocol "http"}})

(amazonica.aws.s3/set-s3client-options 
    (. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true))

(create-bucket credentials "testing")
```

This results in the following error:

```
CompilerException java.lang.IllegalArgumentException: Could not determine best method to invoke for set-s3client-options using arguments (nil)
```

If I execute only the line `(. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true)` then the REPL returns `nil` and is probably why the `set-s3client-options` is failing with the message `using arguments (nil)`.

So this means, my code that attempts to call `setPathStyleAccess` on `(com.amazonaws.services.s3.S3ClientOptions.)` isn't working. How do I successfully call that method?

I've looked at the Java inter-op information and it seems to suggest the code I used (see below) should work, but it clearly doesn't.

```clj
(. (com.amazonaws.services.s3.S3ClientOptions.) setPathStyleAccess true)
```

**Comment by Integralist** [comment]
I've tried to import `(com.amazonaws.services.s3)` but had no luck.

I realised I'm not able to access that namespace by running the following code:

```clj
(keys (ns-publics 'com.amazonaws.services.s3))
```

I thought I'd be able to `use` or `import` this library because it's included as part of Amazonica?

**Comment by Integralist** [comment]
```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3]
        [com.amazonaws.services.s3]))
```

This code will result in an error:

```
CompilerException java.io.FileNotFoundException: Could not locate com/amazonaws/services/s3__init.class or com/amazonaw
s/services/s3.clj on classpath: , compiling:(spurious_aws_sdk_helper/core.clj:1:38)
```

**Comment by Integralist** [comment]
I've also tried...

```clj
(ns spurious-aws-sdk-helper.core
  (:use [amazonica.aws.s3])
  (:import [com.amazonaws.services.s3]))
```

But the import can't find the files:

```
CompilerException java.lang.ClassNotFoundException: com.amazonaws.services.s3
```

**Comment by mcohen01** [comment]
@Integralist pass the same credentials map to both function calls.

```clj
(set-s3client-options credentials :path-style-access true)
(create-bucket credentials "testing")
```

The S3Client is memoized, so basically if you invoke functions in any service specific namespace (e.g. amazonica.aws.s3) with different credentials, then a different *Client is created and used. This corresponds with the Java api as well, if you want to use different credentials you have to new another *Client into existence, i.e. there's no `setCredentials` method on any of the clients.

**Comment by Integralist** [comment]
@mcohen01 thanks that worked! :-)

**Comment by mcohen01** [comment]
Sorry for the time wasted on this. The auth/client config in amazonica evolved over time and is kind of a mess. And I've never removed anything, even the worst bits, like the horrible `defcredential`. If my comment wasn't completely clear, amazonica's abstraction is leaking quite a bit here. In general, I think the preference for Clojure libraries is to explicitly pass any context in to functions, e.g. JDBC connections, rather than implicitly hold it as state somewhere. Amazonica supports both, all functions take a map of credentials (and/or config) as a first argument. The trouble lies in the fact that amazonica also supports all those same function calls with no explicit credentials argument passed in. This seemed to be a valid choice, as with no credentials specified you get the provider chain, where environment, system props, or IAM roles are used. This makes for a nice api, but judging by the number of folks who run into issues with it, I wonder if it's not better to just require the DefaultProviderChain to be explicit as well. In any case, I've updated the docs to try to make it clearer for folks.  3ec5d47cdab815802398a8f0b702016b16e16abc

**Comment by Integralist** [comment]
@mcohen01 Thanks for clarifying. The updated README really helps with understanding what's happening there now :-)
