### ISSUE TITLE
dynamodbv2 cannot put item containing map with one key/value pair where key is one character long

### ISSUE THREAD

**Issue by jmglov** [mcohen01/amazonica#120]
When trying to put an item into a DynamoDB table which contains a map with just one key/value pair, where the key is one character long, one gets an `AmazonServiceException`, as the following example demonstrates:

```clj
(dynamo/put-item :table-name "rs2-dev-match"
                 :item {:id "m1", :foo {:a 1}})
```

The resulting stacktrace:

```
AmazonServiceException Supplied AttributeValue is empty, must contain exactly one of the supported datatypes (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ValidationException; Request ID: DK3M098NKLDNV3LV85AQVHI2QVVV4KQNSO5AEMVJF66Q9ASUAAJG)
	com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1077)
	com.amazonaws.http.AmazonHttpClient.executeOneRequest (AmazonHttpClient.java:725)
	com.amazonaws.http.AmazonHttpClient.executeHelper (AmazonHttpClient.java:460)
	com.amazonaws.http.AmazonHttpClient.execute (AmazonHttpClient.java:295)
	com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.invoke (AmazonDynamoDBClient.java:3106)
	com.amazonaws.services.dynamodbv2.AmazonDynamoDBClient.putItem (AmazonDynamoDBClient.java:1206)
	sun.reflect.NativeMethodAccessorImpl.invoke0 (NativeMethodAccessorImpl.java:-2)
	sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:57)
	sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
	java.lang.reflect.Method.invoke (Method.java:606)
	sun.reflect.GeneratedMethodAccessor21.invoke (:-1)
	sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
```

The issue is the [`amazonica.aws.dynamodbv2/scalar-attribute-value?`](https://github.com/mcohen01/amazonica/blob/d9373fab246b592a981ddaa41e7b6daa22eb6225/src/amazonica/aws/dynamodbv2.clj#L38) function:

```clj
(defn- scalar-attribute-value? [value]
  (and (map? value)
       (= 1 (count value))
       (= 1 (count (name-of-first-key value)))))
```

@jankronquist, can you explain what the purpose of this function is? What is a scalar attribute? Are you looking for things like `{:S "foo"}` or `{:N "bar"}`? If so, this code won't handle `{:BOOL true}` and `{:SS ["foo" "bar"]}`, etc.

Am I misunderstanding the intent of the code?

**Comment by jankronquist** [comment]
The problem is that clojure maps are being coerced into two different things: 
* An AttributeValue representing a map
* An scalar AttributeValue like {:S "foo"}, {:N 5}. Your correct, this does not work with BOOL. 

The reason I added this was to keep backwards compatibility with existing coercions, but there was also some case where the {:S "foo"} was still needed to trigger the coercion. I think is was related to conditions, for example :expected {:someProperty {:value {:s someValue}}}

**Comment by jmglov** [comment]
Could we then change this to the following?

```clj
(defn- scalar-attribute-value? [value]
  (and (map? value)
       (= 1 (count value))
       (contains? #{:s :b :BOOL :SS :BS :n :NS :l :m :NULL} (name-of-first-key value))))
```

**Comment by jankronquist** [comment]
Yes, that would probably make more sense! :-)
