### ISSUE TITLE
Kinesis - How to register checkpoint manually

### ISSUE THREAD

**Issue by bcambel** [mcohen01/amazonica#123]
Hi, 

We are using ```core.async``` to publish events, and write them to disk in batch, and ship it to S3 and we are looking a way to register these checkpoints ( the latest sequence-number ) once we send the data to S3. 

- Is there a way to do it ? 
- What is the best way to do it ? 

And also how can we tell Kinesis client to start from that point ? 

Thanks
Cheers,
Bahadir

**Comment by mcohen01** [comment]
Did you look at the [example](https://github.com/mcohen01/amazonica#kinesis)? The sequence number of each record is available to the function you provide as the RecordProcessor when you start a worker. New workers can be configured to start at InitialPositionInStream.LATEST.
