### ISSUE TITLE
Mistranslation of 'OKActions' to keyword

### ISSUE THREAD

**Issue by neilprosser** [mcohen01/amazonica#124]
CloudWatch uses a field called `OKActions` in their responses to the `describe-alarms` call. When it comes out of Amazonica (via `amazonica.core/camel->keyword`) the response has a keyword of `:okactions`.

[Lettercase](https://github.com/ToBeReplaced/lettercase) translates it to `:ok-actions` (using `lower-hyphen-keyword`) so in my own code I'd bring in the library and use that instead. I understand that might not be the desired approach here. It's likely to make the regular expression a bit more complicated.

**Comment by mcohen01** [comment]
Yeah, I think the problem would be that amazonica's camel to keyword impl (however imperfect) is effectively part of the public api at this point.

**Comment by neilprosser** [comment]
Yeah, that's a shame. I only spotted it because I was trying to take the result of a `describe-alarms` call, `select-keys` from it and turn it into a call to create a new alarm. It just means that people will have to munge the output and know that those keys will need renaming.
