### ISSUE TITLE
SWF: list-domains not working

### ISSUE THREAD

**Issue by jplaza** [mcohen01/amazonica#125]
The parameter it expects is `ListDomainRequest` but this object has an empty constructor.

I've tried:

```clojure
(list-domains)
;; IllegalArgumentException Could not determine best method to invoke for list-domains using arguments null  amazonica.core/intern-function/fn--1520 (core.clj:814)

(list-domains {})
;; AmazonServiceException 1 validation error detected: Value null at 'registrationStatus' failed to satisfy constraint: Member must not be null (Service: AmazonSimpleWorkflow; Status Code: 400; Error Code: ValidationException; Request ID: 88d30619-d4a9-11e4-b6ff-bd5bd357f16f)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1077)

(list-domains :reverse-order true)
;; AmazonServiceException 1 validation error detected: Value null at 'registrationStatus' failed to satisfy constraint: Member must not be null (Service: AmazonSimpleWorkflow; Status Code: 400; Error Code: ValidationException; Request ID: b2511ff2-d4a9-11e4-b571-9df7f0c7c3c1)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1077)
```

**Comment by mcohen01** [comment]
try `(list-domains :reverse-order true : registration-status "REGISTERED")`

**Comment by jplaza** [comment]
It worked!
Thanks!
How you determine what key values args to use in similar cases?

**Comment by mcohen01** [comment]
The appropriate key value pairs for each function are dependent on the underlying Java method that's invoked. Basically, you'll probably need to keep the AWS [Javadocs](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html) open in the browser. This is explained in more detail in the readme.

**Comment by jplaza** [comment]
That's exactly what I'm doing. But as you can see [here](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleworkflow/model/ListDomainsRequest.html) the constructor doesn't expect any parameter.

BTW, thanks a lot for the library! :smile: It's always more pleasant to deal with maps than Java objects.

**Comment by mcohen01** [comment]
Right, so the constructors for any of the *Request objects won't take any params. They'll all have JavaBean getters and setters. The setter names become the map keys you pass.
