### ISSUE TITLE
Kinesis client should support batch upload natively

### ISSUE THREAD

**Issue by hwasungmars** [mcohen01/amazonica#126]
In the `kinesis.clj` only the `put-record` is supported natively, while `put-records` is a direct Java translation.  `put-records` has performance advantage over `put-record` and it is recommended by Amazon.

We should have a Clojure native `put-records` function.

I am willing to have a go if you are too busy at the moment.

**Comment by mcohen01** [comment]
Pull requests are most welcome!

I tend to think putRecords was added in the last version bump of the Java client and I missed it. You should probably be able to call it today, just without being able to pass unwrapped Clojure data structures . So the following will probably work:

```clj
(put-records :stream-name "my-stream"
                     :records [{partition-key "x5h2ch"
                                     :data (ByteBuffer/wrap (nippy/freeze ["foo" "bar" "baz"]))}
                                    {partition-key "x5...."
                                     :data (ByteBuffer/wrap (nippy/freeze ["quux"]))}])
```

**Comment by hwasungmars** [comment]
Yes, you are right.  It does work indeed.  I am not sure how it works though.  How does the call know that it needs to create a `PutRecordsRequest`?  I presume it comes from `core.clj`.  How does it work exactly?
