### ISSUE TITLE
Support for STS Assume Role

### ISSUE THREAD

**Issue by kurtharriger** [mcohen01/amazonica#131]
AssumeRole allows a EC2 instance running in one account to acquire credentials for a role in another amazon account.  We use this to launch instances in our production account from a jenkins server running in our development account.  

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html#assumeRole(com.amazonaws.services.securitytoken.model.AssumeRoleRequest)

http://docs.aws.amazon.com/IAM/latest/UserGuide/roles-walkthrough-crossacct-3-userole.html#roles-walkthrough-crossacct-3-userole-cli

Assume role returns a credential object containing that includes a session token, however the only public way to set credentials in amazonica is using defcredential or with-credentials. This method however ignores the requires session token.

I worked around the issue by subverting private on the *credentials* object using (binding #'amazonica/*credentials* {...}] ...)

**Comment by mcohen01** [comment]
All the functions take an optional credentials map as the first arg, and :session-token is supported. I think https://github.com/mcohen01/amazonica/issues/6 covers it

**Comment by kurtharriger** [comment]
I think this would work as I didn't realize the first parameter could be a credential object, but seems like this should also be supported by with-credentials

**Comment by mcohen01** [comment]
Fixed by 83e38d700db75370ab1ffcf002a615060e75f9d7
