### ISSUE TITLE
May need to call set-endpoint on elasticmapreduce client

### ISSUE THREAD

**Issue by kurtharriger** [mcohen01/amazonica#132]
When running on an EC2 instance using an IAM role for some reason the elasticmapreduce client endpoint is not set correctly or appears to be different than other services for some reason.      

In my code I need to explicitly set the endpoint to query us-west-2, failing to do this results in the emr client defaulting to us-east-1. 
(emr/set-endpoint "https://elasticmapreduce.us-west-2.amazonaws.com")

Although amazonica allows you to specify an endpoint when creating the credentials this is problematic because this endpoint only works for elasticmapreduce calls, thus if I create a credentials object with the above endpoint then I cannot also make calls to s3.  

It is even necessary when using the aws commandline tools to specify the endpoint
```
[ec2-user@schwartzci ~]$ AWS_DEFAULT_REGION=us-west-2 aws emr list-clusters --active
hostname 'elasticmapreduce.us-west-2.amazonaws.com' doesn't match u'us-west-2.elasticmapreduce.amazonaws.com'

[ec2-user@schwartzci ~]$  AWS_DEFAULT_REGION=us-west-2 aws emr list-clusters --active --endpoint http://us-west-2.elasticmapreduce.amazonaws.com
... listing...
```
There is also a weird mismatch between the url for used by the cli us-west-2.elasticmapreduce.amazonaws.com fails with java api vs elasticmapreduce.us-west-2.amazonaws.com which works for java api but fails on cli

I think if I were able to specify the Region with the credentials rather than the endpoint I would be okay since it seems that the Region object seems to use the correct endpoint but the amazonica api did not expose set-region since it was on a parent class no method was generated.

**Comment by mcohen01** [comment]
I think you can just pass {:endpoint "us-west-2"} as the first arg to your EMR functions. Does that not work?

**Comment by kurtharriger** [comment]
Ah, I didn't realize I could specify the endpoint and/or credential object as the first argument.  Also it seems weird that :endpoint is a region rather than an endpoint. Might be more intuitive if this were named :region instead since endpoint via the cli needs to be a fqdn instead.  

But yes, this does work. Thanks
