### ISSUE TITLE
opsworks create-deployment fails with classcastexception

### ISSUE THREAD

**Issue by langalex** [mcohen01/amazonica#139]
I'm trying to run a deployment on opsworks:

```
(create-deployment {
  :stack-id "my-stack-id"
  :command {:name "execute_recipes" :args {"recipes" ["my-recipe-name"]}}
  :instance-ids ["my-instance-id"]})
```

and am getting this error:

```
ClassCastException java.lang.String cannot be cast to java.util.List  com.amazonaws.services.opsworks.model.transform.CreateDeploymentRequestMarshaller.marshall (CreateDeploymentRequestMarshaller.java:101)
```

Am I doing something wrong or is this a bug?

I've tried passings the `:args` in various ways (just a string, a list) but to no avail.

**Comment by mcohen01** [comment]
Ah, sorry, this is a bug. We lose the type, because of erasure I think, in nested collections. Your "recipes" vector comes out as just a string. :(  I'll take a look....

**Comment by mcohen01** [comment]
v 0.3.24 should handle this correctly

**Comment by langalex** [comment]
great, works now. thanks so much.
