### ISSUE TITLE
NoSuchMethodError calling elasticloadbalancing/describe-instance-health

### ISSUE THREAD

**Issue by timgilbert** [mcohen01/amazonica#141]
Hi. Not sure whether I'm calling this function wrong or not, but I'm getting errors trying to call [`describeInstanceHealth()`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancing/AmazonElasticLoadBalancingClient.html#describeInstanceHealth(com.amazonaws.services.elasticloadbalancing.model.DescribeInstanceHealthRequest)) using amazonica.

Here's what I'm trying:

```
$ lein try amazonica "0.3.24"
nREPL server started on port 65321 on host 127.0.0.1 - nrepl://127.0.0.1:65321
REPL-y 0.3.5, nREPL 0.2.6
Clojure 1.6.0
Java HotSpot(TM) 64-Bit Server VM 1.8.0_45-b14
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

user=> (require '[amazonica.aws.elasticloadbalancing :as elb])
nil
user=> (elb/describe-instance-health :load-balancer-name "my-lb-name")

NoSuchMethodError com.amazonaws.AmazonWebServiceClient.beforeMarshalling(Lcom/amazonaws/AmazonWebServiceRequest;)Lcom/amazonaws/AmazonWebServiceRequest;  com.amazonaws.services.elasticloadbalancing.AmazonElasticLoadBalancingClient.describeInstanceHealth (AmazonElasticLoadBalancingClient.java:982)
```

This seems like it should work, and I'm able to run the equivalent operation in the AWS CLI:

```
$ aws --version
aws-cli/1.7.34 Python/2.7.6 Darwin/14.3.0
$ aws elb describe-instance-health --load-balancer-name my-lb-name
{
    "InstanceStates": [
        {
            "InstanceId": "i-xyzzy",
            "ReasonCode": "N/A",
            "State": "InService",
            "Description": "N/A"
        }
    ]
}
```

Any help appreciated, and I'll gladly submit a pull request with an example for the README if I get it working. Thanks!

**Comment by timgilbert** [comment]
Oh, I should also note that I tried upgrading amazonica's AWS-SDK dependency to 1.10.1 but it didn't seem to make a difference, though I might have bolloxed something up when I tried to load it.

**Comment by mcohen01** [comment]
There's probably a dependency issue. What happens if you just add amazonica to your project dependencies, not using lein try?

**Comment by timgilbert** [comment]
Hmm, I think you're right. I'm able to make the above call successfully after making a new project with `lein new` and adding amazonica to it. I'll check my project environment for dependency issues. Thanks!
