### ISSUE TITLE
Cannot use AmazonS3Client/setBucketAcl with AccessControlList parameter

### ISSUE THREAD

**Issue by neilprosser** [mcohen01/amazonica#142]
I'm attempting to create an access control list on an S3 bucket using Amazonica and can't figure out how to trigger the right client method from being picked.

```
> (amazonica.aws.s3/set-bucket-acl "my-bucket-name" {:grant-all ["AuthenticatedUsers" "Read"]})
IllegalArgumentException The ACL parameter must be specified when setting a bucket's ACL  com.amazonaws.services.s3.AmazonS3Client.rejectNull (AmazonS3Client.java:2934)
```

I've stuck a bit of awful `println`ing into the Amazonica code and it looks like it's picking the method (or constructor) which takes the `CannedAccessControlList`. Does Amazonica pick the method based on number of arguments or is it that my AccessControlList map is incorrect?

For reference, the docs:
http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/AmazonS3Client.html#setBucketAcl(java.lang.String,%20com.amazonaws.services.s3.model.AccessControlList)

**Comment by mcohen01** [comment]
You should be able to invoke this now with 0.3.26, but with nested vectors:

```(s3/set-bucket-acl "my-bucket-name" {:grant-all [["AuthenticatedUsers" "Read"]]})```

`grantAllPermissions` takes a seq of Grants, which take a seq of Grantee and Permission. 

But you wouldn't have seen this until you got past the bug. :)  which was as you said, amazonica for the most part can't do too much beyond matching methods based on the number of arguments. That works fine in most cases with AWS, but there are some namespaces, particularly S3, where the clients have overloaded methods with the same arg count. 

Note that there was another bug that was uncovered with this too. The owner field in the ACL class you referenced from the Javadocs appears to be required, despite the fact that the docs say it's for internal use only. So now, that defaults to the current authenticated S3 account owner unless you explicitly supply as Owner.

**Comment by neilprosser** [comment]
Ah great. Thanks for that. That owner thing make sense given what I've seen in the code I'm converting to use Amazonica. That all works fine using `0.3.27`.
