### ISSUE TITLE
amazonica.aws.kinesis/worker! seems to ignore credentials parameter

### ISSUE THREAD

**Issue by markryall** [mcohen01/amazonica#146]
I am trying to get a kinesis worker processing a stream in the non default region and can't determine how to configure the credentials in `amazonica.aws.kinesis/worker!`.

For example, in the following code (deliberately avoiding the standard `AWS_*` environment variables), I do get the list of streams in the region specified by `$KINESIS_REGION` (including the one I want to process) but get an access failure message for the worker.

This was working ok (without credentials) when the stream was in us-east-1. 

```clojure
(ns reflex-consumer.core
  (:require [amazonica.aws.kinesis :as k]
            [amazonica.core :refer [with-credential]])
  (:gen-class))

(def kinesis-stream (System/getenv "KINESIS_STREAM"))
(def kinesis-app (System/getenv "KINESIS_APP"))

(defn -main
  []
  (with-credential [(System/getenv "KINESIS_ACCESS_KEY_ID") (System/getenv "KINESIS_SECRET_ACCESS_KEY")  (System/getenv "KINESIS_REGION")]
    (println (k/list-streams))
    (k/worker! :app kinesis-app
         :stream kinesis-stream
         :credentials [(System/getenv "KINESIS_ACCESS_KEY_ID") (System/getenv "KINESIS_SECRET_ACCESS_KEY")  (System/getenv "KINESIS_REGION")]
         :checkpoint false
         :processor (fn [records]
                      (doseq [row records]
                        (println (:data row)
                                 (:sequence-number row)
                                 (:partition-key row)))))))
```

I assume `with-credential` has no effect on `k/worker! ` for some thread local related reason?

**Comment by mcohen01** [comment]
You can configure the underlying kinesis client lib with the `region-name` key as well as any of the others listed [here](https://github.com/mcohen01/amazonica/blob/master/src/amazonica/aws/kinesis.clj#L141).

**Comment by markryall** [comment]
Thanks for your help Michael

I can't work out why but all of those keys passed to the kinesis client library are ignored except for :app, and :stream - I can pass any arbitrary values and the region and endpoint remain us-east-1.

**Comment by mcohen01** [comment]
Can you post your code?

**Comment by markryall** [comment]
```clojure

**Comment by mcohen01** [comment]
Ah, sorry, I totally missed that last night the first time you posted that.

So if I run:

```clj
(create-stream {:endpoint "kinesis.us-west-1.amazonaws.com"} "my-stream" 1)
(def w  (worker :app "kinesis-app"
         :stream "my-stream"
         :endpoint "kinesis.us-west-1.amazonaws.com"
         :region-name "us-west-1" 
         :checkpoint false 
         :processor #(println %)))
(future (.run (first w)))
```

I'll see logging like:

```
Jul 21, 2015 9:51:09 AM com.amazonaws.services.kinesis.leases.impl.LeaseCoordinator <init>
INFO: With failover time 10000ms and epsilon 25ms, LeaseCoordinator will renew leases every 3308ms and take leases every 20050ms
Jul 21, 2015 9:51:09 AM com.amazonaws.internal.DefaultServiceEndpointBuilder getServiceEndpoint
INFO: {kinesis, us-west-1} was not found in region metadata, trying to construct an endpoint using the standard pattern for this region: 'kinesis.us-west-1.amazonaws.com'.
Jul 21, 2015 9:51:09 AM com.amazonaws.services.kinesis.clientlibrary.lib.worker.Worker <init>
WARNING: Received configuration for both region name as us-west-1, and Amazon Kinesis endpoint as kinesis.us-west-1.amazonaws.com. Amazon Kinesis endpoint will overwrite region name.
```

And I'll in fact be reading and writing from a Kinesis stream in us-west-1.

**Comment by markryall** [comment]
Oh crap - PEBCAK - I realise I am not running the latest version of amazonica.

The latest version works perfectly - I am happily processing streams in whichever region catches my eye.

I'm very sorry to have wasted your time and thanks for your great work. :(

**Comment by mcohen01** [comment]
No worries Mark :)
