### ISSUE TITLE
VPC public ip

### ISSUE THREAD

**Issue by narkisr** [mcohen01/amazonica#147]
Following this issue https://forums.aws.amazon.com/thread.jspa?threadID=78584

When attaching a public ip to a vpc instance you can't use the constructor of AssociateAddressRequest but rather use the default empty ctor and call two setters

I haven't found a way to do that using Amazonica

Thanks

**Comment by mcohen01** [comment]
Yes, you won't be able to do this, as amazonica simply delegates to the Java client.
