### ISSUE TITLE
Misleading exception message while trying to connect an not existing bucket (S3)

### ISSUE THREAD

**Issue by emrehan** [mcohen01/amazonica#150]
Hey,

Whereas s3api aws cli gives `NoSuchBucket` error if we try to connect to an not existing bucket; amazonica gives the following one: `SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided.`

**Comment by rschmitt** [comment]
What if you try specifying the region explicitly? You may be connecting to one region and signing for a different region. (This assumes that you're using sigv4; s3api in the aws cli might not be, at least not for the version you're using.)

**Comment by mcohen01** [comment]
This is what I get:

```clj
(s3/list-objects "path-that-i-own/foobar-doesnt-exist")
```
```
AmazonS3Exception The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: B615C2A794A243AD)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1160)
```


```clj
(s3/list-objects "global-key-i-dont-own")
```

```
AmazonS3Exception Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied; Request ID: A4671F38D4A31E47)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1160)
```

**Comment by emrehan** [comment]
I was calling the following without specifying the region:

```clojure
(s3/put-object :bucket-name bucket
                   :key dir
                   :metadata {:server-side-encryption "AES256"
                              :content-length (count data-bytes)}
                   :input-stream data-input-stream)
```
where bucket was `""`.

I've figured out the problem for myself but opened the issue because a better error message could save other people some time in future :)

**Comment by mcohen01** [comment]
Not much we can do about the error messages as we just delegate to the Java client.

**Comment by emrehan** [comment]
@mcohen01 It's okay if the error is coming from AWS Java SDK. 

Thanks for the project!
