### ISSUE TITLE
sqs/delete-message returns nil

### ISSUE THREAD

**Issue by ilyabe** [mcohen01/amazonica#151]
When I make a delete-message request using amazonica, the message is deleted successfully, but the function returns nil. The DeleteMessage request directly via the SQS API returns a RequestId.

http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_DeleteMessage.html

Would it be possible to have the amazonica delete-message return the RequestId as well?

**Comment by mcohen01** [comment]
Probably every call you make with the cli shows you the request id, but amazonica delegates to the Java client library methods, which in this case [returns void](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html#deleteMessage(java.lang.String,%20java.lang.String).
