### ISSUE TITLE
Dependency conflict

### ISSUE THREAD

**Issue by rwilson** [mcohen01/amazonica#152]
Amazonica depends on `[org.apache.httpcomponents/httpclient "4.3.3"]` and `[com.amazonaws/aws-java-sdk "1.10.5.1" :exclusions [joda-time]]`, but `com.amazonaws/aws-java-sdk "1.10.5.1"` depends on `[org.apache.httpcomponents/httpclient "4.3.6"]`. 

As far as I can tell, it doesn't seem to cause a functional problem, but it adds a lot of noise to `lein deps :tree`. I'd suggest either updating Amazonica to `httpclient "4.3.6"` or adding `org.apache.httpcomponents/httpclient` to the `:exclusions` for the `aws-java-sdk` dependency.

**Comment by mcohen01** [comment]
Good catch. Thanks!
