### ISSUE TITLE
EMR release label support

### ISSUE THREAD

**Issue by rschmitt** [mcohen01/amazonica#154]
Amazonica (version 0.3.31) seems to ignore any `:resource-label` argument specified as part of a `run-job-flow` request--either that, or it's always supplying an `:ami-version`, overriding even an explicit `nil`. Either way, it's making it impossible to use EMR 4.0.0.

**Comment by rschmitt** [comment]
This may not actually be a bug in Amazonica. I'll see if I can get something working using the SDK directly, and then see if that translates to an Amazonica invocation.

**Comment by rschmitt** [comment]
Well, here's the problem:

`java.lang.IllegalArgumentException: No matching method found: setReleaseLabel for class com.amazonaws.services.elasticmapreduce.model.RunJobFlowRequest`

I thought that Amazonica imported a more recent SDK than that.

**Comment by mcohen01** [comment]
0.3.32 should work for you

**Comment by rschmitt** [comment]
And indeed it does.
