### ISSUE TITLE
non-amazon endpoint with client-side encryption

### ISSUE THREAD

**Issue by ohlo** [mcohen01/amazonica#157]
Hi, I have found using client-side encryption more difficult than when using no encryption. 

I have been able to get it working by getting a result of #'amazonica.core/encryption-client and calling .setEndPoint and .setPathStyleAccess on it. but clearly this is depending on internals. If there is a way to set these values as you would for the non encryption version (i.e. amazonica.core/amazon-client) that would be helpful.

thanks

**Comment by mcohen01** [comment]
Is something like below not working for you?

```clj
(def key-pair
    (let [kg (KeyPairGenerator/getInstance "RSA")]
      (.initialize kg 1024 (SecureRandom.))
      (.generateKeyPair kg)))

;; put object with client side encryption
(put-object :bucket-name bucket1
            :key "foo"
            :encryption {:key-pair key-pair}
            :file upload-file)

;; get object and decrypt
(get-object :bucket-name bucket1
            :encryption {:key-pair key-pair}
            :key "foo")))))
```

**Comment by ohlo** [comment]
the thing is we need to set the endpoint and the path-style, since we are
not using amazon. those seem to be easily set when not using client-side
auth, by using defcredential and set-client-options.

On Thu, Sep 3, 2015 at 6:31 PM, Michael Cohen <notifications@github.com>
wrote:

> Is something like below not working for you?
>
> (def key-pair
>     (let [kg (KeyPairGenerator/getInstance "RSA")]
>       (.initialize kg 1024 (SecureRandom.))
>       (.generateKeyPair kg)))
> ;; put object with client side encryption
> (put-object :bucket-name bucket1
>             :key "foo"
>             :encryption {:key-pair key-pair}
>             :file upload-file)
> ;; get object and decrypt
> (get-object :bucket-name bucket1
>             :encryption {:key-pair key-pair}
>             :key "foo")))))
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcohen01/amazonica/issues/157#issuecomment-137521401>.
>



-- 
@henryw374

**Comment by mcohen01** [comment]
Ok, so:

```clj
(def ep {:endpoint "..."})
(set-s3client-options ep :path-style-access true)
(put-object ep
            :bucket-name bucket1
            :key "foo"
            :encryption {:key-pair key-pair}
            :file upload-file)
```

**Comment by ohlo** [comment]
unfortunately the AmazonS3EncryptionClient instance this creates does not
have the endpoint set.

core/encryption-client* fn does not call .setEndpoint, but core/amazon-client*
does

On Thu, Sep 3, 2015 at 8:36 PM, Michael Cohen <notifications@github.com>
wrote:

> Ok, so:
>
> (def ep {:endpoint "..."})
> (set-s3client-options ep :path-style-access true)
> (put-object ep
>             :bucket-name bucket1
>             :key "foo"
>             :encryption {:key-pair key-pair}
>             :file upload-file)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mcohen01/amazonica/issues/157#issuecomment-137552458>.
>



-- 
@henryw374

**Comment by mcohen01** [comment]
Ooops, you're right!  Can you try with 0.3.33?

**Comment by ohlo** [comment]
Great, that is working now, thanks. 

Btw, setting path-style access for an encryption client I can now do, like this, ie adding the :encryption arg to the parameters:

(s3/set-s3client-options creds
                                    :path-style-access true
                                    :encryption {:key-pair the-key-pair-you-will-use})
