### ISSUE TITLE
Using amazonica with stubs

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#158]
I'd like to write some code that uses amazonica. I'm trying to write tests for it. Someone has already gone through the trouble of writing those stubs: https://github.com/bizo/aws-java-sdk-stubs

Since amazonica uses reflection, it shouldn't be too tricky; a cursory review of the code suggests I just need to call `set-client` a bunch of times, possibly on separate namespaces. Is that accurate?

**Comment by mcohen01** [comment]
Well, I'm not sure what the question is exactly, but yes, `set-client` is the "entry point" for everything - it interns some vars into the specific namespace for whatever AWS service you're looking to use.

**Comment by lvh** [comment]
Okay, great; thanks :)
