### ISSUE TITLE
Specifiy the starting key when listing object in S3 bucket

### ISSUE THREAD

**Issue by JarrodCTaylor** [mcohen01/amazonica#160]
I have a large S3 bucket that has well over the 1000 item limit that is returned as a default from aws. The documentation http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketGET.html says that you can specify a `marker` that will be used as the starting key for the returned items allowing you to have some pagination like functionality. 

Is there a way to pass a marker to the `list-objects` function?

**Comment by mcohen01** [comment]
:marker

**Comment by JarrodCTaylor** [comment]
Ha ok well that was obvious. Thanks.
