### ISSUE TITLE
Version 0.3.34 isn't in Clojars

### ISSUE THREAD

**Issue by neilprosser** [mcohen01/amazonica#161]
Sorry to be a pain. I can see you merged the pull-request and bumped the version but I can't see it in Clojars.

**Comment by mcohen01** [comment]
Hey Neil, sorry I'm traveling with a loaner laptop and don't have my clojars gpg keys. I tried to change project.clj to not require signing but couldn't get it to work. If you can give me the correct snippet I can push a release, otherwise not until October 8.

**Comment by neilprosser** [comment]
Ah. No worries. It's not that urgent. I know in the past I've forgotten to hit the promote button on releases!

From looking at the leiningen documentation it seems like the required snippet would be:

```clojure
:deploy-repositories [["releases" {:url "https://clojars.org/repo/"
                                   :sign-releases false}]]
```

However, I'm happy to wait so you can sign a proper release rather than have to rush something out which isn't signed.

**Comment by mcohen01** [comment]
Released :)
