### ISSUE TITLE
Cloudfront Signed URL

### ISSUE THREAD

**Issue by continuata** [mcohen01/amazonica#164]
Is there a way to generate a Cloudfront Signed URL?

I'm using this for S3 (which works great):
```clj
(s3/set-s3client-options {:path-style-access true})
(aws/defcredential s3_accesskey s3_secretkey)
(s3/generate-presigned-url bucket key (-> 6 hours from-now))
```
Is there anything similar for Cloudfront using the Cloudfront keypair?

**Comment by mcohen01** [comment]
I'm pretty sure you would have to just use CloudFrontUrlSigner directly

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudfront/CloudFrontUrlSigner.html

**Comment by continuata** [comment]
Hi Michael, sorry I missed your response ... thanks so much for that, I'll try your suggested approach.

**Comment by jdkealy** [comment]
could someone provide an example on how to do this in clojure ?
