### ISSUE TITLE
Shutting down Kinesis worker

### ISSUE THREAD

**Issue by lsnape** [mcohen01/amazonica#168]
Calling the `amazon.aws.kinesis/worker!` function with args starts a worker and returns a `worker-id`, which I assume is meant to be used as a handle to the running worker object, but it's unclear how that `worker-id` is then used to retrieve the running instance to, say, shutdown the worker.

I've got around this by implementing my own version of `amazon.aws.kinesis/worker!`, which returns the `worker` object so I can kill it when I stop the system.

Is there a way to refer to a running worker instance just by using the `worker-id`? If not, it would be helpful if the `worker!` function returned the object rather than the string identifier?

 Happy to make any changes required and submit a PR.

**Comment by mcohen01** [comment]
You can call `worker` (without the exclamation) to get back the actual worker.

**Comment by lsnape** [comment]
If that's the case, and if I understand correctly, then the following should shutdown a running worker:

```
(defn start-working!
  []
  (let [worker-id (amk/worker! worker-config)]
    (reset! client-worker-id worker-id)))

(defn stop-working! []
  (let [[worker _] (amk/worker (merge worker-config
                                      {:worker-id @client-worker-id}))]
    (.shutdown worker)
    (reset! client-worker-id nil)))
```

But it doesn't work: logging output continues and I get no indication that the worker has stopped :( If, however, I retain the worker object, calling shutdown does kill it as expected.

**Comment by mcohen01** [comment]
In this example you're starting two different workers - one with `worker!` (in `start-working!`), and the second in `stop-working!` with `worker`. Your atom needs to hold the reference to the worker you create in `start-working`.

**Comment by lsnape** [comment]
Okay yes I understand. Can't quite see the rationale for `worker!` just returning the created worker id though. Storing the worker in an atom is fine as a solution though.

Thanks :)
