### ISSUE TITLE
compile errors 

### ISSUE THREAD

**Issue by jdkealy** [mcohen01/amazonica#169]
Hi, 

I'm trying to use this lib and getting errors when i run the repl. Any ideas? This is my stacktrace / project deps: 

Johns-MacBook-Pro:veda johnkealy$ lein repl
#error {
 :cause com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V
 :via
 [{:type clojure.lang.Compiler$CompilerException
   :message java.lang.NoSuchMethodError: com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V, compiling:(core.clj:210:1)
   :at [clojure.lang.Compiler$DefExpr eval Compiler.java 452]}
  {:type java.lang.NoSuchMethodError
   :message com.fasterxml.jackson.core.JsonParser.setCurrentValue(Ljava/lang/Object;)V
   :at [com.fasterxml.jackson.databind.deser.BeanDeserializer vanillaDeserialize BeanDeserializer.java 243]}]
 :trace
 [[com.fasterxml.jackson.databind.deser.BeanDeserializer vanillaDeserialize BeanDeserializer.java 243]
  [com.fasterxml.jackson.databind.deser.BeanDeserializer deserialize BeanDeserializer.java 136]
  [com.fasterxml.jackson.databind.ObjectMapper _readMapAndClose ObjectMapper.java 3562]
  [com.fasterxml.jackson.databind.ObjectMapper readValue ObjectMapper.java 2531]
  [com.amazonaws.internal.config.InternalConfig loadfrom InternalConfig.java 233]
  [com.amazonaws.internal.config.InternalConfig load InternalConfig.java 251]
  [com.amazonaws.internal.config.InternalConfig$Factory <clinit> InternalConfig.java 308]
  [com.amazonaws.util.VersionInfoUtils userAgent VersionInfoUtils.java 139]
  [com.amazonaws.util.VersionInfoUtils initializeUserAgent VersionInfoUtils.java 134]
  [com.amazonaws.util.VersionInfoUtils getUserAgent VersionInfoUtils.java 95]
  [com.amazonaws.ClientConfiguration <clinit> ClientConfiguration.java 42]
  [java.lang.Class forName0 Class.java -2]
  [java.lang.Class forName Class.java 348]
  [clojure.lang.RT classForName RT.java 2154]
  [clojure.lang.RT classForName RT.java 2163]
  [amazonica.core$get_client_configuration <clinit> core.clj 210]
  [sun.reflect.NativeConstructorAccessorImpl newInstance0 NativeConstructorAccessorImpl.java -2]
  [sun.reflect.NativeConstructorAccessorImpl newInstance NativeConstructorAccessorImpl.java 62]
  [sun.reflect.DelegatingConstructorAccessorImpl newInstance DelegatingConstructorAccessorImpl.java 45]
  [java.lang.reflect.Constructor newInstance Constructor.java 422]
  [java.lang.Class newInstance Class.java 442]
  [clojure.lang.Compiler$ObjExpr eval Compiler.java 4843]
  [clojure.lang.Compiler$DefExpr eval Compiler.java 439]
  [clojure.lang.Compiler eval Compiler.java 6787]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 634]
  [clojure.core$use doInvoke core.clj 5843]
  [clojure.lang.RestFn invoke RestFn.java 421]
  [amazonica.aws.s3$eval5459$loading__5340__auto____5460 invoke s3.clj 1]
  [amazonica.aws.s3$eval5459 invoke s3.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$require doInvoke core.clj 5832]
  [clojure.lang.RestFn invoke RestFn.java 551]
  [veda.groups$eval5453$loading__5340__auto____5454 invoke groups.clj 1]
  [veda.groups$eval5453 invoke groups.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$require doInvoke core.clj 5832]
  [clojure.lang.RestFn invoke RestFn.java 551]
  [veda.users$eval5447$loading__5340__auto____5448 invoke users.clj 1]
  [veda.users$eval5447 invoke users.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$require doInvoke core.clj 5832]
  [clojure.lang.RestFn invoke RestFn.java 1289]
  [veda.handler$eval20$loading__5340__auto____21 invoke handler.clj 1]
  [veda.handler$eval20 invoke handler.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 634]
  [clojure.core$use doInvoke core.clj 5843]
  [clojure.lang.RestFn invoke RestFn.java 436]
  [veda.repl$eval14$loading__5340__auto____15 invoke repl.clj 1]
  [veda.repl$eval14 invoke repl.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.RT loadResourceScript RT.java 371]
  [clojure.lang.RT loadResourceScript RT.java 362]
  [clojure.lang.RT load RT.java 446]
  [clojure.lang.RT load RT.java 412]
  [clojure.core$load$fn__5448 invoke core.clj 5866]
  [clojure.core$load doInvoke core.clj 5865]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [clojure.core$load_one invoke core.clj 5671]
  [clojure.core$load_lib$fn__5397 invoke core.clj 5711]
  [clojure.core$load_lib doInvoke core.clj 5710]
  [clojure.lang.RestFn applyTo RestFn.java 142]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$load_libs doInvoke core.clj 5749]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.core$apply invoke core.clj 632]
  [clojure.core$require doInvoke core.clj 5832]
  [clojure.lang.RestFn invoke RestFn.java 408]
  [user$eval5 invoke form-init7463140786795716327.clj 1]
  [clojure.lang.Compiler eval Compiler.java 6782]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler eval Compiler.java 6771]
  [clojure.lang.Compiler load Compiler.java 7227]
  [clojure.lang.Compiler loadFile Compiler.java 7165]
  [clojure.main$load_script invoke main.clj 275]
  [clojure.main$init_opt invoke main.clj 280]
  [clojure.main$initialize invoke main.clj 308]
  [clojure.main$null_opt invoke main.clj 343]
  [clojure.main$main doInvoke main.clj 421]
  [clojure.lang.RestFn invoke RestFn.java 421]
  [clojure.lang.Var invoke Var.java 383]
  [clojure.lang.AFn applyToHelper AFn.java 156]
  [clojure.lang.Var applyTo Var.java 700]
  [clojure.main main main.java 37]]}

My current deps are: 

  :dependencies [[org.clojure/clojure "1.7.0"]
                 [ring-server "0.4.0"]
                 [reagent "0.5.1"]
                 [reagent-forms "0.5.12"]
                 [reagent-utils "0.1.5"]
                 [ring "1.4.0"]
                 [ring/ring-defaults "0.1.5"]
                 [fogus/ring-edn "0.3.0"]
                 [prone "0.8.2"]
                 [clj-time "0.11.0"]
                 [crypto-random "1.2.0"]
                 [cljs-ajax "0.3.13"]
                 [crypto-password "0.1.3"]
                 [cheshire "5.3.1"]
                 [compojure "1.4.0"]
                 [hiccup "1.0.5"]
                 [environ "1.0.1"]
                 ;[clj-aws-s3 "0.3.10"]
                 [amazonica "0.3.34"]
                 [org.clojure/clojurescript "1.7.122" :scope "provided"]
                 [org.clojure/core.async "0.1.346.0-17112a-alpha"]
                 [secretary "1.2.3"]
                 [org.postgresql/postgresql "9.4-1202-jdbc41"]
                 [org.clojure/java.jdbc "0.4.2"]]

**Comment by mcohen01** [comment]
It's a dependency issue with jackson. See issue #112 and issue #135. I would guess cheshire, but could be some other lib causing. lein deps :tree should tell you where to look.

**Comment by mcohen01** [comment]
is this resolved then?
