### ISSUE TITLE
Make default serialization from kinesis and kinesis-firehose swappable.

### ISSUE THREAD

**Issue by jwhitlark** [mcohen01/amazonica#180]
The default serializer for kinesis is nippy, and for firehose (for sequences) is csv.  I'd like to make it easily swappable, and in the long run, get rid of the dependency on nippy if you're not planning on using it.

I'm happy to do the work myself, but I wanted to see people's thoughts on the subject.

My plan would be to make the encoder swappable, but defaulting to nippy (with a deprecation warning, and instructions on how to set things up if you want to continue using nippy), and then remove it with the next major version.

Thoughts?

**Comment by mcohen01** [comment]
Nippy seemed like a good default at the time, but it's already "swappable" in the sense that you just pass a ByteBuffer to `put-record` instead of Clojure data. What facilities on top of that did you have in mind?

**Comment by jwhitlark** [comment]
To be honest, I'd like to have the default not require nippy and its dependencies.  We're using transit as the format, and including it in a number of projects, some of which are quite large, and it causes some problems.  It's just a little too opinionated for such a general library, I think.  

I'd be happy to put together a pull request, and show you what I mean, but wanted to get your opinion first. I just didn't want to do the work if there was no possibility of it being considered.

**Comment by mcohen01** [comment]
I don't have strong preferences either way, and if you and Joe Wilk think nippy's not the best serialization choice, good enough for me. And you're probably right about removing it even for no other reason than to clean up the dependencies.

**Comment by jwhitlark** [comment]
I never had the time to work on this, and I don't think it's as relevant as I once did.  If someone else has a concern with it, they can re-open it.
