### ISSUE TITLE
Exclude portions of the aws-sdk

### ISSUE THREAD

**Issue by jwhitlark** [mcohen01/amazonica#181]
Beginning in version 1.9.0, the aws sdk is modular, (see http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/java-dg-using-maven.html)

Using the following dependencies, I was able to get s3 calls working:
``` clojure
:dependencies [[org.clojure/clojure "1.7.0"]
               [amazonica "0.3.39" :exclusions [com.amazonaws/aws-java-sdk]]
               [com.amazonaws/aws-java-sdk-core "1.10.28"]
               [com.amazonaws/aws-java-sdk-s3 "1.10.28"]
               [com.amazonaws/aws-java-sdk-cloudsearch "1.10.28"]
               [com.amazonaws/aws-java-sdk-lambda "1.10.28"]]
```

Which will make amazonica much nicer for some of my use cases, (aws lambda jobs, etc.), as it cuts over 115M off the size of the uberjar.

Is there any reason this wouldn't work in all cases?  If not, we should add it to the documentation.

**Comment by mcohen01** [comment]
I don't see why it wouldn't work. Although I only see the full AWS SDK adding 35mb to the uberjar (if I just `lein new foo` and add amazonica as a dep and uberjar it.)

**Comment by mcohen01** [comment]
"only 35mb" lol

**Comment by jwhitlark** [comment]
Oops. Thanks, though. It'll still help.

"Assumptions are like dogs. Mine just bit me."

**Comment by mcohen01** [comment]
removed everything but core a1de64567635de83ff463788e595c736eb215420
