### ISSUE TITLE
S3 transfer with object meta data

### ISSUE THREAD

**Issue by erez-rabih** [mcohen01/amazonica#196]
Hi,

I am currently using s3transfer upload method in order to upload files to s3 and register progress listeners.
I'm using the simplest form: ```(s3/upload "my-bucket" "s3-destination" my-file)```

Is it possible to use the upload method providing object metadata like server-side-encryption?

Thanks for the help

**Comment by mcohen01** [comment]
The methods on the Amazon*Client class of the Java SDK are sometimes overloaded, with one or more methods taking scalar arguments, as you're using here, in addition to a [method](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#upload(com.amazonaws.services.s3.model.PutObjectRequest, com.amazonaws.services.s3.transfer.internal.S3ProgressListener)) that takes a one arg *Request object. So in that case you might do something like:
```clj
(s3/upload
  :bucket-name "my-bucket" 
  :key "s3-destination"
  :file my-file
  :metadata {:SSE-algorithm "AES256"})
```

**Comment by erez-rabih** [comment]
@mcohen01 Thanks that appear to work.

I still can't find which constructor of PutObjectRequest derives the map you provided to the upload method. There is one constructor with 4 arguments but it has an input stream instead of a file:
```java
PutObjectRequest(String bucketName, String key, InputStream input, ObjectMetadata metadata)
```

**Comment by mcohen01** [comment]
Amazonica [tries](https://github.com/mcohen01/amazonica/blob/master/src/amazonica/core.clj#L388) to find a no-arg constructor and in the absence of one simply selects the first one found, passing nulls for each argument. The hash values you specify in your clojure function call end up on the javabeans strictly via setter invocations.
