### ISSUE TITLE
Expecting attribute to not exist?

### ISSUE THREAD

**Issue by stephanebruckert** [mcohen01/amazonica#197]
I'm trying to insert a `clientId` such as it can only be inserted once.

```
(ddb/put-item cred
      :table-name table-name
      :expected {:clientId {:exists false}}
      :item payload)
```

I suspect `:expected {:clientId {:exists false}}` to be ignored because the same `clientId` is inserted multiple times. What is the correct way to expect a non-existing clientId in DynamoDB?

**Comment by mcohen01** [comment]
Not sure...maybe

```clj
(ddb/put-item cred
      :table-name table-name
      :condition-expression "attribute_exists(clientId)"
      :item payload)
```

**Comment by stephanebruckert** [comment]
**TL;NR** define a simple primary key (aka. Partition Key) instead of a composite key (aka. Partition Key and Sort Key).

So your code was "understood" by DynamoDB as there was no error message. But because of that, no item were inserted at all. Indeed, the condition meant: as long as "attribute exists", insert it. So what would have been what I wanted was:

      :condition-expression "attribute_not_exists(clientId)"

But that gave me an error (which is strange, why wouldn't `attribute_exists(clientId)` throw an error then? hum, probably because it doesn't ask DynamoDB to do something that kind of go against the meaning of its primary key definition).

I soon realised that what I needed was a table with a **simple primary key**:

> **Partition Key**—A simple primary key, composed of one attribute, known as the partition key. DynamoDB uses the partition key's value as input to an internal hash function; the output from the hash function determine the partition where the item will be stored. **No two items in a table can have the same partition key value.**

Then the item is expected to be put without "condition-expression":

```
(ddb/put-item cred
      :table-name table-name
      :item payload)
```

And putting the item twice will do an update.

**Comment by stephanebruckert** [comment]
You probably meant:

      :condition-expression "attribute_not_exists(clientId)"

And it works! I still had to define a simple primary key (aka. Partition Key) instead of a composite key (aka. Partition Key and Sort Key).

> **Partition Key**—A simple primary key, composed of one attribute, known as the partition key. DynamoDB uses the partition key's value as input to an internal hash function; the output from the hash function determine the partition where the item will be stored. **No two items in a table can have the same partition key value.**

However... I am getting the following error (yes, even though it does what I want):

> The conditional request failed (Service: AmazonDynamoDBv2; Status Code: 400; Error Code: ConditionalCheckFailedException;

Any idea? Thank you!

**Comment by stephanebruckert** [comment]
Just realised that it was only Amazon's way of saying "all is fine, but your condition was false"...
Thanks for your help @mcohen01

**Comment by mcohen01** [comment]
Were you able to get this working?

**Comment by stephanebruckert** [comment]
Yes, we can close it even though this question remains: http://stackoverflow.com/questions/35096312/the-conditional-request-failed-whereas-the-condition-works

Thanks.
