### ISSUE TITLE
list-objects throws an exception

### ISSUE THREAD

**Issue by l1x** [mcohen01/amazonica#198]
I have a weird problem with the S3 library. It throws the following when I am trying to use list-objects.

I can list buckets, create a new bucket but I can't list the objects. 

```Clojure
(s4/list-buckets cred)
```
Debug log show AWS is happy with credentials.

```
2016-01-29 21:16:38,326 DEBUG com.amazonaws.request Received successful response: 200, AWS Request ID: 68F116B28790D2E1
2016-01-29 21:16:38,326 DEBUG com.amazonaws.requestId AWS Request ID: 68F116B28790D2E1
[{:name "back-to-back", :owner ....}]
```
```Clojure
(s4/list-objects cred {:bucket-name "my-bucket" :prefix ""})
```

```
IllegalArgumentException The bucket name parameter must be specified when listing objects in a bucket  com.amazonaws.services.s3.AmazonS3Client.rejectNull
```

What am I doing wrong?

**Comment by l1x** [comment]
It seems this works:

```Clojure
(s3/list-objects "my-bukcet)
```

It appears to me that the invocation with credentials does not work, eg. this fails:

```Clojure
(list-objects cred :bucket-name bucket1 :prefix "")
```

Might have been also failing here:
Test [url](https://github.com/mcohen01/amazonica/blob/master/test/amazonica/test/s3.clj#L91)

**Comment by mcohen01** [comment]
Can you confirm what's in `cred`?

**Comment by l1x** [comment]
Thanks for coming back on this! cred holds my credentials in the following form:

```Clojure
{:aws_access_key_id A...., :aws_secret_access_key S.....}
```

**Comment by mcohen01** [comment]
It should be `{:access-key "..." :secret-key "..."}`

See the [auth section](https://github.com/mcohen01/amazonica#authentication)
