### ISSUE TITLE
example of how to avoid this warning when downloading / uploading files from S3? 

### ISSUE THREAD

**Issue by jdkealy** [mcohen01/amazonica#205]
When I download or upload files to /  from S3, i get this warning 

WARNING: No content length specified for stream data. Stream contents will be buffered in memory and could result in out of memory errors.

I believe it's affecting my RAM utilization and I get some poorly transferred files. I'm sorry if this isn't an amazonica issue, but perhaps you guys could point in the right direction for transferring files? I've seen no clojure threads that address this.

**Comment by mcohen01** [comment]
You need to provide `content-length` in the `object-metadata` or specify a File rather than an InputStream.

**Comment by mrpronerd** [comment]
So then how do you stream data to S3.   If you just have an input stream to pass through for it to copy you do not have any way to know the length without reading the entire dataset in to memory.

**Comment by mcohen01** [comment]
`new File(path).length()`?

**Comment by mrpronerd** [comment]
That is loading the file from a file system, and puts the file in memory.   This question is about streaming the data.   In which case you have an input stream so you have no way to know the size of the data set.

**Comment by mcohen01** [comment]
you can use `File().length()` to get the size to pass as `content-length` and still upload using the `InputStream`

**Comment by mrpronerd** [comment]
That is still going to load the data into memory since for that to read from the stream to that File object 
 which puts the data in memory.  If you read from the input stream you load the data in memory, and if you do not then you do not know the length.

**Comment by mcohen01** [comment]
if you have the file on disk somewhere you're fine, File.length doesn't read the file. If you just have an InputStream from....wherever, then yeah, not sure what to tell you...
