### ISSUE TITLE
Timeout waiting for connection from pool 

### ISSUE THREAD

**Issue by jdkealy** [mcohen01/amazonica#206]
Hi, 

I introduced some code that gets metadata about S3 objects, but doing this over and over again results in the above error. Reading the Java sdk board, it looks like you need to close the connection after calling (get-object) but I don't see a way to do that. How would I do that ?

**Comment by jdkealy** [comment]
More about why I'm using get-object... I need to know the file size in bytes. If there's a way to do that without calling (get-object) that would be cool too! 
Calling the below results in the error in the subject line. 
```
(-> (get-object cred bucket path)
      :object-metadata 
      :content-length ) 
  
```

**Comment by mcohen01** [comment]
You need to close the InputStream

```clj
(let [obj (get-object cred bucket path)
      md (:object-metadata obj)]
  (.close obj)
  (:content-length md))
```

**Comment by jdkealy** [comment]
Thank you!

**Comment by ktsujister** [comment]
Hi,
If you know that you are only getting metadata, doing below is also fine.
```clojure
(require '[amazonica.aws.s3 :as s3)
(s3/get-object-metadata s3-bucket s3-key)
```
