### ISSUE TITLE
Something seems wrong with the encoding of Kinesis stream data

### ISSUE THREAD

**Issue by d4goxn** [mcohen01/amazonica#211]
When I put an event into a stream using the AWS CLI, I can pass JSON in and get it back out, after decoding from base64. When I try to put an event using Amazonica, the event data gets mangled.

```clojure
(kinesis/put-record "ad-stream" {:ad-id "some-id"} "parition-key"))
```

creates an event with a base64 encoded data field of `"TlBZCAAAABXwBhsAAAACagVhZC1pZGkHc29tZS1pZA=="`, which decodes to

```json
NP�jad-idisome-id
```

If I JSON encode the data first:

```clojure
(kinesis/put-record "ad-stream" (json/write-str {:ad-id "some-id-2"}) "parition-key")
```

then I get a event data that contains a good string, but with a prefix of junk characters:

```json
NPi{"ad-id":"some-id-2"}
```

It was mentioned #180 that a ByteStream can be passed to `put-record` as the event data parameter, so I will try that, but the docs and the tests show plain Clojure data structures being used directly.

**Comment by d4goxn** [comment]
Related to #100, but I can't quite tell if this is a duplicate or not.

**Comment by d4goxn** [comment]
Passing a ByteBuffer of a JSON string as the record data works for me.

```clojure
(kinesis/put-record "ad-stream" (-> {:ad-id "ad-stream"} json/write-str .getBytes ByteBuffer/wrap) "parition-key")
```

Record data: `"eyJhZC1pZCI6ImFkLXN0cmVhbSJ9"`, decodes to: 

```json
{"ad-id":"ad-stream"}
```

**Comment by mcohen01** [comment]
If you pass Clojure data amazonica assumes you read and write to the stream using amazonica, and serializes the data with nippy. Passing a ByteBuffer makes no assumptions about what might read from the stream, so you can use anything. 

https://github.com/mcohen01/amazonica#kinesis
