### ISSUE TITLE
KMS decrypt, encrypt

### ISSUE THREAD

**Issue by octavioturra** [mcohen01/amazonica#212]
I can't find documentation to use KMS encrypt and decrypt.

**Comment by mcohen01** [comment]
You may need to look at the [Javadocs](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/kms/AWSKMSClient.html) and translate the setters into Clojure keyword val pairs as described in the readme.

**Comment by octaviogb** [comment]
Thank you
