### ISSUE TITLE
Add lambda list-function hook

### ISSUE THREAD

**Issue by eigenhombre** [mcohen01/amazonica#213]
Currently you can create or call lambda functions.
The AWS API supports listing functions as well.  It'd be nice to have this in Amazonica.

**Comment by mcohen01** [comment]
```clj
(require '[amazonica.aws.lambda :as l])
(l/list-functions)
```
Is this not what you're after?

**Comment by eigenhombre** [comment]
@mcohen01 ah, that could be it. The fact that it wasn't in the example docs or in `src/amazonica/aws/lambda.clj` threw me, I guess. Thanks!
