### ISSUE TITLE
s3transfer/copy doesn't marshall Copy result

### ISSUE THREAD

**Issue by mattflo-outpace** [mcohen01/amazonica#227]
The `s3transfer/copy` function doesn't return a `Copy` result, thus making it impossible to `waitForCopyResult`. The copy does succeed, but you can't see the result or block for the copy to complete.

**Comment by mattflo-outpace** [comment]
https://github.com/mcohen01/amazonica/pulls

**Comment by mcohen01** [comment]
fixed in 0.3.65
