### ISSUE TITLE
Error with ACL in S3 while passing creds in parameter

### ISSUE THREAD

**Issue by marcvincenti** [mcohen01/amazonica#228]
Hello, i just want to report a little error in s3.

When i want to perform this :
```
(put-object cred
            :bucket-name "mybucket"
            :key filename
            :input-stream (input-stream (.toByteArray out))
            :metadata {:content-type "image/png" 
                       :content-length (count (.toByteArray out))}
            :access-control-list {:grant-permission ["AllUsers" "Read"]})
```
I get the following error : **Error setting :access-control-list: Unable to load AWS credentials from any provider in the chain. Perhaps the value isn't compatible with the setter?** 
This error only show when i try to update ACL.

So, I tested using `defcredential` and it actually works, but is there a way to avoid using the chain ?

**Comment by mcohen01** [comment]
Would you mind trying again with v0.3.67 and without using `defcredential`? AWS used to complain when the ACL did not have the S3 account owner set on it, so when we coerced the `:access-control-list` to the Javabean, we'd also call `get-s3account-owner` behind the scenes to take care of that transparently. Unfortunately, from the place where we're coercing into Java objects, there is not really any good way to get access to the function args passed in the original function (in this case, the credentials passed to `put-object`), so we invoke `get-s3account-owner` without explicit credentials, looking for them in the `DefaultProviderChain`, hence the error you were seeing. I'm curious to know if when you run under 0.3.67 if the call succeeds for you. Note that you should see "Unable to set account owner for ACL" printed to the console.

**Comment by marcvincenti** [comment]
Yes, the files are uploading to S3 buckets.
And in the console there is the following message "[WARN] Unable to set account owner for ACL:  Unable to load AWS credentials from any provider in the chain"
Thank you ! :+1:
