### ISSUE TITLE
Unable to invoke lambda function due to response parsing error

### ISSUE THREAD

**Issue by brabster** [mcohen01/amazonica#229]
Hi there,

Using latest amazonica 0.3.66 and aws lambda sdk 1.11.18, I'm having problems invoking a lambda function.

```clojure
(lambda/invoke {:region "eu-west-1"} 
  :function-name "arn:aws:lambda:eu-west-1:1234567890:function:my-lambda" 
  :payload "{}"
  :invocation-type "DryRun")
```

```
AmazonServiceException Unable to parse HTTP response content (Service: AWSLambda; Status Code: 400; Error Code: null; Request ID: null)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1377)
```

I've also tried with the deprecated ```lambda/invoke-async```, same issue

**Comment by brabster** [comment]
Running against https://github.com/watson/http-echo-server (great idea!!) via :endpoint and the call works, returning a payload and a status code.

**Comment by mcohen01** [comment]
You can try with v0.3.70 which includes the latest AWS Java SDK. If you're still getting an error, can you post the full stacktrace?

**Comment by brabster** [comment]
Sorry for the delay.

Retried with latest .70 version (I exclude all and then bring in what I'm using, so I bumped those to aws sdk 1.11.20 to match). Error is now

```
NoSuchMethodError com.amazonaws.protocol.json.JsonClientMetadata.withBaseServiceExceptionClass(Ljava/lang/Class;)Lcom/amazonaws/protocol/json/JsonClientMetadata;  com.amazonaws.services.lambda.AWSLambdaClient.<init> (AWSLambdaClient.java:176)
```

**Comment by brabster** [comment]
Did get the invoke call working direct against the AWS SDK:

```clojure
(defn invoke-async [region function-arn payload]
  (let [c (doto (AWSLambdaClient.)
            (.setRegion (Region/getRegion (Regions/fromName region))))
        r (doto (InvokeRequest.)
            (.setFunctionName function-arn)
            (.setPayload payload)
            (.setInvocationType "Event"))]
    (.invoke c r)))
```
