### ISSUE TITLE
amazonica.aws.s3/set-bucket-notification-configuration always throws?

### ISSUE THREAD

**Issue by gareth625** [mcohen01/amazonica#230]
I've encountered an issue when trying to use `amazonica.aws.s3/set-bucket-notification-configuration`. The function chain inevitably ends in trying to construct an instance of `com.amazonaws.services.s3.model.NotificationConfiguration` which is an abstract class and there are subclasses for the AWS services you can configure notifications for. When Amazonica tries to call `amazonica.core/new-instance` to create a new instance of an `NotificationConfiguration` object it throws exception as the class has no constructor e.g. is an abstract class and `amazonica.core/best-constructor` returns nil. I think in this case it's `constuctor-args` that throws as it's passed nil.

My call (wrapped in an amazonica.core/with-credential) is
```
(amazonica.aws.s3/set-bucket-notification-configuration
     "my.bucket.name"
     {:configurations {"my-custom-event-name"
                       {:queue-ARN "arn:aws:sqs:eu-west-1:123456789012:my-sqs-queue-name"
                        :add-event "ObjectCreatedByPut"}}})
```

Some debug and exception
```
TRACE t32248: | | | | | | | (amazonica.core/new-instance com.amazonaws.services.s3.model.NotificationConfiguration)
TRACE t32249: | | | | | | | | (amazonica.core/best-constructor com.amazonaws.services.s3.model.NotificationConfiguration)
TRACE t32249: | | | | | | | | => nil
TRACE t32250: | | | | | | | | (amazonica.core/constructor-args nil)
```
```
RuntimeException Failed to create an instance of com.amazonaws.services.s3.model.NotificationConfiguration from {"my-custom-event-name" {:queue-ARN "arn:aws:sqs:eu-west-1:123456789012:my-sqs-queue-name", :add-event "ObjectCreatedByPut"}} due to java.lang.NullPointerException. Make sure the data matches an existing constructor and setters.  amazonica.core/unmarshall (core.clj:569)

**Comment by mcohen01** [comment]
v0.3.69 is on clojars. See the [readme](https://github.com/mcohen01/amazonica#s3) for the exact form of the function calls.

**Comment by gareth625** [comment]
Thanks for such a quick turn around on this. The tagging is now just working for me but I haven't quite got the notifications working correctly.

```
(ac/with-credential (:credentials config)
  (s3/set-bucket-notification-configuration
    :bucket-name "my.bucket"
    :notification-configuration
    {:configurations
      {:some-config-name
        {:queue "arn:aws:sqs:eu-west-1:0123456789012:my-queue"
         :events #{"ObjectCreatedByPut"}}}}))
```

returns: `The event is not supported for notifications` and

```
(ac/with-credential (:credentials config)
  (s3/set-bucket-notification-configuration
    :bucket-name "my.bucket"
    :notification-configuration
    {:configurations
      {:some-config-name
        {:queue "arn:aws:sqs:eu-west-1:0123456789012:my-queue"
         :events #{"s3:ObjectCreated:Put"}}}}))
```

returns: `Unable to validate the following destination configurations`.

It feels like I've got something trivially incorrect. What does `:some-config-name` represent? is the notification name?

Thanks

**Comment by mcohen01** [comment]
Yeah, `:some-config-name` is just the name, it can be anything. Are the queue and bucket already existent, meaning, you're not creating them on the fly just before you attempt to create the notification?

**Comment by gareth625** [comment]
Sorry to jump around a bit but I wanted to get my tag set code implemented before sinking more time into the notifications. Unfortunately I think there's a bug there. You can't set more than one tag set with the current implementation, it's come up against [this](https://stackoverflow.com/questions/30521046/malformedxml-when-tagging-an-s3-bucket) bug in the AWS S3 SDK.

The following clj code works:
```
(ac/with-credential (:credentials config)
    (s3/set-bucket-tagging-configuration
     :bucket-name "my.bucket"
     :tagging-configuration {:tag-sets [["CreatedBy" "gareth"]]})
    (s3/get-bucket-tagging-configuration "my.bucket"))
```

but the following:
```
(ac/with-credential (:credentials config)
    (s3/set-bucket-tagging-configuration
     :bucket-name "my.bucket"
     :tagging-configuration {:tag-sets [["Formation" "notlive"] ["CreatedBy" "gareth"]]})
    (s3/get-bucket-tagging-configuration "my.bucket"))
```

gives the `XML you provided was not well-formed or did not validate against our published schema` exception.

Using Java interop directly it's the difference between:
```
(let [s3-client        (doto (AmazonS3Client. (BasicAWSCredentials.
                                                                      (get-in config [:credentials :access-key])
                                                                      (get-in config [:credentials :secret-key])))
                               (.setEndpoint "s3-eu-west-1.amazonaws.com"))
       tag-set           (TagSet. {"Formation" "notlive" "CreatedBy" "gareth"})
       tagging-conf (doto (BucketTaggingConfiguration.)
                               (.setTagSets (doto (java.util.ArrayList.) (.add tag-set))))]
    (.setBucketTaggingConfiguration
     s3-client
     (SetBucketTaggingConfigurationRequest. "my.bucket" tagging-conf)))
    (s3/get-bucket-tagging-configuration "my-bucket"))
```

which works, and
```
(let [s3-client        (doto (AmazonS3Client. (BasicAWSCredentials.
                                                                      (get-in config [:credentials :access-key])
                                                                      (get-in config [:credentials :secret-key])))
                                (.setEndpoint "s3-eu-west-1.amazonaws.com"))
       tag-set-0       (TagSet. {"Formation" "notlive"})
       tag-set-1       (TagSet. {"CreatedBy" "gareth"})
       tagging-conf (doto (BucketTaggingConfiguration.)
                       (.setTagSets (doto (java.util.ArrayList.) (.add tag-set-0) (.add tag-set-1)))]
    (.setBucketTaggingConfiguration
     s3-client
     (SetBucketTaggingConfigurationRequest. "my.bucket" tagging-conf))
    (s3/get-bucket-tagging-configuration "my.bucket"))
```

which does not. I believe from the trace that Amazonica is doing the latter. S3 really seem to want to test your patients.

Thanks.

**Comment by gareth625** [comment]
The notification configuration turned out to be because I had subtly messed up the permission policy on my SQS queue. Forgot the "Resources" key whose value is the queue itself! That's working now but I had to use the `s3:ObjectCreated:Put` form of the event which surprised me.

**Comment by mcohen01** [comment]
So basically `:tag-sets` works, as long as you only specify one tag pair?

**Comment by mcohen01** [comment]
v0.3.72 should let you specify multiple TagSets with something like:
```
(s3/set-bucket-tagging-configuration
   :bucket-name "my.bucket.name"
   :tagging-configuration
     {:tag-sets [{:Formation "notlive" :foo "bar" :baz "quux"}]})
```

**Comment by gareth625** [comment]
Yes that's right. I probably should have added it means you could only have set one tag for a bucket as it's a set to match those you provide. You're not adding new tags to an existing set on the bucket i.e. you can't work around it by just calling it n times with one tag set per call.

Thanks so much for your help over the last few days. Really appreciate your prompt responses (prompter than mine). Annoyingly I can't test it right now but will do in the morning, the commit looks good though :)

**Comment by gareth625** [comment]
Successfully tested, thanks!
