### ISSUE TITLE
Not reading ~/.aws/credentials in lein repl

### ISSUE THREAD

**Issue by mustafashabib** [mcohen01/amazonica#235]
Hey all

Just curious if anyone has seen this behavior -- using `lein repl` and with my aws credentials in my environment vars, everything works as expected. 

When I get rid of my env vars and add my credentials to `~/.aws/credentials` I get 

``` clojure
dev=> (ns com.quartethealth.s3test
 #_=>   (:use [amazonica.aws.s3]
 #_=>          [amazonica.aws.s3transfer]))
nil
com.quartethealth.s3test=>  (create-bucket "amazonia-creds-test")

AmazonClientException Unable to load AWS credentials from any provider in the chain  com.amazonaws.auth.AWSCredentialsProviderChain.getCredentials (AWSCredentialsProviderChain.java:131)
```

Any idea why?

**Comment by mcohen01** [comment]
Maybe check permissions on that file, and check that you have a `[default]` profile in it?

**Comment by mustafashabib** [comment]
Thanks for the response- will check permissions when I'm back at a keyboard. `[default]` is set properly already tho. 

M

**Comment by warrenronsiek** [comment]
Ran into this when running tests in a repl via Intellij-Cursive. Solved the issue by setting AWS env variables inside the repl run configuration.
