### ISSUE TITLE
S3 Transfer Acceleration

### ISSUE THREAD

**Issue by pabielicki** [mcohen01/amazonica#238]
Hi, 
is there any way to use accelerated transfer for s3?
By default it should be done by adjust endpoit or set in config, but i have no idea how i can reach it in amazonica.

**Comment by mcohen01** [comment]
You can set the endpoint by passing a map with an :endpoint key as the first arg

**Comment by wkisielewicz** [comment]
Hi,

bucket addressing / endpoint to accelerate looks like this: `my-bucket.s3-accelerate.amazonaws.com`
In my config file I have `:endpoint "eu-central-1`", should I change it to the version which indicates the accelerate? How then resolve problem with region?

Thanks

**Comment by mcohen01** [comment]
Well, this is sort of a special case...

```clojure
(import com.amazonaws.regions.Region)
(import com.amazonaws.regions.Regions)
(-> "eu-central-1"
      Regions/fromName
      Region/getRegion
      s3/set-region)
```

**Comment by deepxg** [comment]
Can you go into any more detail here? All I get from the above region fiddling code is "Unable to find a region via the region provider chain", and S3 operations with the accelerated endpoint throw the same error.
