### ISSUE TITLE
sqs/get-queue-attributes does not accept credentials argument

### ISSUE THREAD

**Issue by hanshuebner** [mcohen01/amazonica#239]
Unlike the other API functions, `sqs/get-queue-attributes` does not accept a credentials argument which makes it fall back to whatever has been established as default credentials in the AWS API.  Can this be fixed easily?

**Comment by mcohen01** [comment]
Can you post your code? Either version of the underlying Java method should work.

**Comment by hanshuebner** [comment]
We verified that it actually works, so please disregard this issue.  Sorry.
