### ISSUE TITLE
sqs/get-queue-attributes does not accept credentials argument

### ISSUE THREAD

**Issue by hanshuebner** [mcohen01/amazonica#241]
The subject says it all (this time I'm posting the right function name :) ).  Can this be fixed easily?  I have trouble understanding how this function is created in the first place, as `M-.` lands me at some seemingly unrelated function.

**Comment by hanshuebner** [comment]
A possible workaround is to explicitly pass the attribute-names argument:

`(sqs/get-queue-attributes credentials queue-url ["All"])`

**Comment by mcohen01** [comment]
The Java method is overloaded so there are a few ways to call it via amazonica, including a few different permutations given that we support enclosed or unenclosed key/value parameters. The following invocations all work:

```clj
(q/get-queue-attributes
  {:attribute-names ["All"]
   :queue-url url})
(q/get-queue-attributes
  cred
  {:attribute-names ["All"]
   :queue-url url})

(q/get-queue-attributes
  :attribute-names ["All"] :queue-url url)
(q/get-queue-attributes
  cred
  :attribute-names ["All"] :queue-url url)

(q/get-queue-attributes url ["All"])
(q/get-queue-attributes cred url ["All"])
```
