### ISSUE TITLE
Simpleworkflow Missing Classes

### ISSUE THREAD

**Issue by oubiwann** [mcohen01/amazonica#244]
I'm brand-new to amazonica, so I may have missed something, but it seems that the only functions available in the simpleworkflow namespace are the client methods. 

There are other classes needed in order to use Clojure protocols and implementations in a workflow (e.g., `com.amazonaws.services.simpleworkflow.flow.*`) -- furthermore, some of those (`flow.ActivityWorker`, `flow.WorkflowWorker`) need to be passed the simpleworkflow client instance. It looks like amazonica's treatment of the kinesis namespace addresses analogous complexities, though more (and different) would be needed for full simpleworkflow support.

Do you have any interest in seeing code which supports full use of simpleworkflow added to amazonica? (Or would you rather folks just use `com.amazonaws.services.simpleworkflow` and Java interop?)

If the former, I'd be willing to work on this ...

Updated with dev tasks:

* Discovery
  * [x] Get the [sample workflow app](http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/getting-started-example-helloworldworkflow.html) in Java to compile and run ([code](https://github.com/clojusc/amazonica-swf-examples/tree/master/src/java/clojusc/aws/examples/swf/javaapp), [docs](https://clojusc.github.io/amazonica-swf-examples/current/30-hello-world-javaapp.html))
    * [x] Set up Eclipse (sadly, this is required), AspectJ, load-time weaving
    * [x] Generate additional classes using AspectJ and SWF annotations
  * [x] Explore feasibility of generating clients in Clojure vs. Eclispe and AspecJ in Java (see https://github.com/clojusc/amazonica-swf-examples/issues/1)
    * [ ] ~~Convert generated Java to Clojure~~
  * [x] Read through links in detail (provided by @mcohen01 below)
  * [ ] ~~Map features needed by swf to existing features in amazonica~~
  * [ ] ~~Identify missing features~~

**Comment by mcohen01** [comment]
I would merge anything you'd care to contribute, I don't know anything about SimpleWorkflow.

**Comment by oubiwann** [comment]
Sweet. I'll do a crash course on the amazonica codebase and then put together a dev plan (really a bullet list of tasks).

Thanks!

**Comment by mcohen01** [comment]
[this description](https://github.com/mcohen01/amazonica/issues/190#issuecomment-168413613) might help explain things a tiny bit, even though it's in the context of DynamoDB, but it applies the same for SWF

**Comment by oubiwann** [comment]
Oh, that's *very* useful. Thanks.

**Comment by mcohen01** [comment]
I looked at the SWF javadocs for 2 minutes and I'm guessing that you'll need to make use of `register-coercions` and `marshall` primarily. See https://github.com/mcohen01/amazonica#extension-points and https://github.com/mcohen01/amazonica/blob/master/src/amazonica/aws/dynamodbv2.clj for references. Basically, `register-coercions` allows you to define how Clojure data is converted into specific Java objects, e.g. the `flow.*` classes, and `marshall` allows you to define the opposite, how Java objects returned from the AWS Java SDK are converted to Clojure data.  I suspect you'll use `register-coercions` extensively and `marshall` not nearly as much (if the Java objects are pojos with getters and setters you won't need to explicitly define how they're marshalled.

**Comment by oubiwann** [comment]
Sadly, there is an enormous amount of Java code that is generated using Eclipse, AspecJ, and some special SWF built tools that Amazon created for developers using the SWF Framework ... From what I can tell, that tool chain is actually *required* in order to develop SWF apps in Java :-( Upon reflection (no pun intended), this makes sense: it's the sort of metaprogramming that Java is terrible at (so it can use all the "help" it can get). While Clojure is obviously a good fit for this problem space, it may end up being an awful lot of code that doesn't follow the typical amazonica approach (client utility).

I'll hack on it and see if I can hit the sweet spot of generality + concise code and usage. If I can, then it might still be a good candidate for a feature addition to amazonica ...

**Comment by oubiwann** [comment]
Phew. I did some deep-diving. Did eventually end up finding this project in the aws Github org:
 * https://github.com/aws/aws-swf-flow-library

This seems to be the direction that Java support is heading for Simpleworkflow apps, even though [the docs](http://docs.aws.amazon.com/amazonswf/latest/awsflowguide/setup.html) point to a fairly old Java maven artifact (aws-swf-build-tools). Supporting this in Clojure will be fairly cumbersome. The most straight-forward way is to `gen-class` everything, essentially duplicating Java class files in corresponding Clojure `gen-class`ed namespaces (but not idiomatic, FP Clojure). That being said, there seem to be [open issues](https://github.com/aws/aws-swf-flow-library/issues) with the fairly new aws-swf-flow-library, up to and including connection/timeout failures that cause workflows to not complete.

Taking this a step towards idiomatic Clojure, one could essentially implement a flow framework (which could then be included as part of amazonica). This is what the Python (in boto) and Ruby communities have done. This would entail a great deal of work, mostly due to the rather boilerplate-heavy approach taken for supporting the SWF service.

Finally, having read reports of other software engineers who have had to support SWF in production using non-supported flow frameworks (e.g., C# and F#), while they got things working and it suited their needs in the short term, in the long run they ended up abandoning SWF in favor of the far more flexible combination of SQS, Lambda, and Kinesis -- allowing them to create a custom workflow much more easily and maintainably than suffering through the use of what seems to be an over-engineered service (SWF).

My own quick, though a bit deep, investigations support this analysis. As such, I will close this ticket and beaver on with an SQS + Lambda solution.
