### ISSUE TITLE
What is the purpose of show-functions?

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#249]
This fn is added to every AWS ns. I've found the source code:

https://github.com/mcohen01/amazonica/blob/6c9256a9a88ff37d87fe836a6d7a47074560ff79/src/amazonica/core.clj#L930-L935

It appears to be private, but not used internally. I'm not sure if this is intentional, but when I eval e.g. `(@#'amazonica.aws.elasticsearch/show-functions)` I just get a bunch of nils, and the names of the corresponding functions are println'd. Is this just for debugging?

**Comment by mcohen01** [comment]
You can call `show-functions`in any namespace and it will simply print all the top level vars
