### ISSUE TITLE
#'amazonica.aws.ec2/describe-egress-only-internet-gateways can't be called

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#251]
```
(#'amazonica.aws.ec2/describe-egress-only-internet-gateways)
java.lang.IllegalArgumentException: Could not determine best method to invoke for describe-egress-only-internet-gateways using arguments null
```

Based on the signature of what appears to be the underlying Java method, it should be fine to call this with no arguments (that just lists all of your egress-only internet gateways). With the same credentials, via AWS CLI, I get the following error:

```
An error occurred (OperationNotPermitted) when calling the DescribeEgressOnlyInternetGateways operation: User 12345 is not permitted to perform this operation
```

Given that based on my understanding of the code, the former error with amazonica means no requests were attempted, so this ostensibly seems like a separate bug.

**Comment by lvh** [comment]
The same thing appears to be true for `(#'amazonica.aws.ec2/describe-nat-gateways)`. The commonality between these two is that they take an optionally empty Request object, I guess?

**Comment by mcohen01** [comment]
You just need to provide an empty map (that will be coerced into the empty `Request` object, like so: `(ec2/describe-egress-only-internet-gateways {})`.

**Comment by lvh** [comment]
Thanks! So if I understand correctly the underlying distinction here is if there's a nullary vs unary underlying method arity? Is there some way to figure out from the Request object what's mandatory and what isn't?

**Comment by mcohen01** [comment]
> So if I understand correctly the underlying distinction here is if there's a nullary vs unary underlying method arity?

Right. The Java SDK used to have a few examples (e.g. S3) of overloaded methods with nullary and unary arities, but they seem to have moved away from that, towards a model with a single method that takes a *Request object. 

> Is there some way to figure out from the Request object what's mandatory and what isn't?

I would guess if you find the generic REST docs it would be specified in there.
