### ISSUE TITLE
Consider adding the underlying method to generated var metadata

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#252]
I appreciate that generating fns with "correct" arities/type hints might be a little tricky (and perhaps that could be done over time for some fns), but it would be helpful for people inspecting/reflecting if at least the method object was made accessible via metadata.

(I am volunteering to do this work if you agree it's an appropriate feature.)

**Comment by mcohen01** [comment]
By "method object" do you mean the AWS Client, e.g. `AWSEc2Client`?

**Comment by lvh** [comment]
Sorry, I meant the java.lang.reflect.Methods, as in the value of `methods` in this snippet:

https://github.com/mcohen01/amazonica/blob/master/src/amazonica/core.clj#L896-L909

**Comment by mcohen01** [comment]
Ah, I get it now. Folks have asked for access to the *Client a couple times before, which would be useful in certain edge cases I guess. But, horses for courses I guess... Lack of docs/introspection in the repl is probably the weakest point of this library. Anything would be an improvement over what exists now.

https://github.com/mcohen01/amazonica/issues/170

**Comment by lvh** [comment]
#254 adds both the client and the methods.
