### ISSUE TITLE
camel->keyword is incorrect for words with acronyms

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#256]
Some examples of this problem:

```
;; #'amazonica.aws.identitymanagement/list-mfadevices
;; #'amazonica.aws.identitymanagement/list-open-idconnect-providers
;; #'amazonica.aws.identitymanagement/list-samlproviders
;; #'amazonica.aws.identitymanagement/list-sshpublic-keys
;; #'amazonica.aws.identitymanagement/list-virtual-mfadevices
;; #'amazonica.aws.iot/describe-cacertificate
;; #'amazonica.aws.iot/list-cacertificates
;; #'amazonica.aws.rds/describe-dbcluster-parameter-groups
;; #'amazonica.aws.rds/describe-dbcluster-snapshots
;; #'amazonica.aws.rds/describe-dbclusters
;; #'amazonica.aws.rds/describe-dbengine-versions
;; #'amazonica.aws.rds/describe-dbinstances
;; #'amazonica.aws.rds/describe-dbparameter-groups
;; #'amazonica.aws.rds/describe-dbsecurity-groups
;; #'amazonica.aws.rds/describe-dbsnapshots
;; #'amazonica.aws.rds/describe-dbsubnet-groups
```

I think it should instead be: `#"[A-Z]+(?=[A-Z]|$)|[A-Z][a-z]*"`.

**Comment by mcohen01** [comment]
Yeah, the var naming capitalization is not perfect, but any fix would have to add new vars with the improved naming into the namespace alongside the vars with the original naming scheme.

**Comment by lvh** [comment]
How do you feel about using camel-snake-kebab, a third party library, to implement this? (I'm happy to make this PR, I just want to make it likely to be accepted first.)

I can also just implement both. Looks like the inverse one (keyword->camel) is correct regardless.

I'm assuming it's also OK to mark the "old" kinds with some metadata? Regardless, because I have code that enumerates these namespaces, I need some way to tell the duplicates apart -- I can do that via the method metadata if need be.

**Comment by mcohen01** [comment]
Well, I'm very hesitant to make a change this risky. It would help a lot if you could also write some kind of test that enumerates the interned vars from each namespace, so that we could compare with the previous version to prove all the vars that were there previously are still there.

**Comment by lvh** [comment]
The risk you're referring to is just that an old var would become unavailable and the change would accidentally break people's code, right? I would just unconditionally intern both, but I'd be happy to write the test.

Unrelatedly: I took the Travis CI PR not being merged as a hint that you're not interested in gating CI, so that's why I didn't focus on testing. I'd be happy to take that list I opened the issue with and create a test checking that those vars still exist :)

**Comment by mcohen01** [comment]
>The risk you're referring to is just that an old var would become unavailable and the change would accidentally break people's code, right? 

Yep

>I took the Travis CI PR not being merged as a hint that you're not interested in gating CI

Yeah, sorry I forgot about that one. Running all the tests via `lein test` (versus running a single namespace's tests, one at a time) hasn't worked in some time. I should really try to get that working, and Travis would be a good catalyst to do that, I just haven't really had time. 

It doesn't necessarily have to be a test, just some code that enumerates all the public vars in each namespace, that you could run against the current version and your feature branch to make sure all the existing vars are still there. It's ugly and messy to keep the old ones around, but hey, I f_cked up the naming way back when and now we're stuck with it....

**Comment by lvh** [comment]
OK, gotcha :) No need to apologize! This is an open source project! I didn't complain about it before because I  was trying not to be a jerk :) I'll write it as a test anyway so it stays useful in the future :)

**Comment by lvh** [comment]
Found another weird case:

* `#'amazonica.aws.storagegateway/describe-storedi-scsivolumes`
* `#'amazonica.aws.storagegateway/describe-cachedi-scsivolumes`

**Comment by lvh** [comment]
PR fixing this is up, with, as far as I can tell, no backwards compatibility issues and hopefully enough tests to convince anyone else of that fact :D
