### ISSUE TITLE
com.amazonaws.SdkClientException: Unable to marshall request to JSON: clojure.lang.Keyword cannot be cast to java.lang.String

### ISSUE THREAD

**Issue by marcvincenti** [mcohen01/amazonica#259]
Hello,

in amazonica.aws.machinelearning, i am actually usiing the function _predict_, but it throws this error because of the record map : 

> ERROR in (machinelearning) (PredictRequestMarshaller.java:92)
com.amazonaws.SdkClientException: Unable to marshall request to JSON: clojure.lang.Keyword cannot be cast to java.lang.String

However, if all key in __record__ map are Strings instead of keywords everything works fine.

I've tried to add a fix for this but i'm struggling with the _IMarshall_ protocol. I don't get it.
This is in "machinelearning.clj"  : 
```
(extend-protocol amz/IMarshall
  PredictRequest
  (marshall [obj]
    (let [records (.getRecord obj)
          new-rec (into {} (for [[k v] records] [(name k) v]))]
      (assoc obj :records new-rec))))
```

**Comment by mcohen01** [comment]
`(clojure.walk/stringify-keys)` ?

**Comment by marcvincenti** [comment]
The point is I get the same error and it didn't seem that the marshall function is used.
Does the extend-protocol work alone ? (I don't understand everything in dynamodbv2.clj)
But thanks for `(clojure.walk/stringify-keys)`, i didn't know about this one.

**Comment by mcohen01** [comment]
`IMarshall` handles going from Java -> Clojure. `register-coercions` handles going from Clojure -> Java. I guess this is a little confusing, the thinking was you marshal Java objects to Clojure data and coerce Clojure data into Java objects. Oh well...."two hard problems in computer science..."

The other issue was that `register-coercions` would not even work in this case without the changes to `core.clj`, as it was never designed to coerce the arguments to the top level AWS service method into an AWS *Request bean. The is the first instance where we've ever needed to do that. 

Anyhow, `0.3.84` is available on clojars. That should let you use keywords as map keys without issue.

**Comment by marcvincenti** [comment]
Okay thank you for your help and explanations.
I don't know if it really was an issue, but i really enjoy this project and i started learning Clojure recently,
so i tried to patch it myself to commit after.
