### ISSUE TITLE
Different results from cli and repl

### ISSUE THREAD

**Issue by Willyfrog** [mcohen01/amazonica#260]
## Context

I've set up a couple of profiles and I have a different response from running the same operation in the repl than with the aws cli tool

### repl
```
kongfu.aws> cred
{:profile "gvaya"}
kongfu.aws> (ebs/describe-applications cred)
{:applications []}
```

### aws cli

I'll use wc to hide details, but you can see that is displaying data

```
$ aws --profile gvaya --output json  elasticbeanstalk describe-applications | wc -l
354
```

## Some extra details: 

I don't have default profile, I set the default via environment variable.

The other profile I have is the one that seems to be being used, as it has less permissions but matches the results from cli and amazonica
 ```
$ aws --profile circleci --output json  elasticbeanstalk describe-applications
{
    "Applications": []
}
```

What can I try/configure to see if there is a problem with my configuration or where should I start looking in case it's a bug? Do you need any extra details?

**Comment by Willyfrog** [comment]
A little bit of extra testing leads me to believe that I need to specify the `:endpoint` even though it's defined in the profile. I would have believed it would be included by reading the credentials.

```clj
kongfu.aws> (def cred {:profile "gvaya" :endpoint "eu-west-1"})
kongfu.aws> (count (:environments (ebs/describe-environments cred)))
# => 8
```

**Comment by mcohen01** [comment]
Yeah, you need to specify the `:endpoint` key as well unfortunately, even if you've got a `region` key in the credentials file profile. Amazonica does instantiate a `ProfileCredentialsProvider` which is passed to the *Client, but I'm not sure why the region is not honored.
