### ISSUE TITLE
Memoizing client objects is bad for multi-tenant apps

### ISSUE THREAD

**Issue by codahale** [mcohen01/amazonica#262]
I have an app which uses many credentials to access a variety of accounts, and the use of `memoize` in those conditions is basically a memory leak.

Any chance you could make the memoization configurable, so I could use a Guava cache w/ max size and expiration to store the client objects?

**Comment by mcohen01** [comment]
Something like https://github.com/mcohen01/amazonica/pull/263 ?

**Comment by mcohen01** [comment]
Fixed via https://github.com/mcohen01/amazonica/pull/264
