### ISSUE TITLE
describe-hosted-connections not bound

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#271]
I'm not sure why.  Evaling: #'amazonica.aws.directconnect/describe-hosted-connection yields:

```
Unable to resolve var: amazonica.aws.directconnect/describe-hosted-connections in this context
```

... even though that NS is loaded and I see other fns and the Java client has that method:

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/directconnect/AmazonDirectConnect.html#describeHostedConnections-com.amazonaws.services.directconnect.model.DescribeHostedConnectionsRequest-

**Comment by mcohen01** [comment]
probably need to bump the sdk dependency

**Comment by lvh** [comment]
Can confirm; works fine with `[com.amazonaws/aws-java-sdk "1.11.98" :exclusions [joda-time]]`.

**Comment by lvh** [comment]
I guess we'll close this and just bump the SDK on the next release?

**Comment by mcohen01** [comment]
`0.3.88` is out on clojars with the latest AWS SDK 1fe8489e77ec5cecbefd3a3b5075d9344e761470
