### ISSUE TITLE
kinesisfirehose/list-delivery-streams can't be called

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#275]
All args are allegedly optional:

```clojure
> (#'amazonica.aws.kinesisfirehose/list-delivery-streams {})
IllegalArgumentException Could not determine best method to invoke for list-delivery-streams using arguments (nil {})  amazonica.core/intern-function/fn--38895 (core.clj:931)
> (#'amazonica.aws.kinesisfirehose/list-delivery-streams)
IllegalArgumentException Could not determine best method to invoke for list-delivery-streams using arguments (nil :limit 10000)  amazonica.core/intern-function/fn--38895 (core.clj:931)
```

Fortunately, there's some metadata available now for debugging ;)

```clojure
> (meta #'amazonica.aws.kinesisfirehose/list-delivery-streams)
{:amazonica/client
 com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient,
 :amazonica/methods
 [#object[java.lang.reflect.Method 0x6ae14b74 "public com.amazonaws.services.kinesisfirehose.model.ListDeliveryStreamsResult com.amazonaws.services.kinesisfirehose.AmazonKinesisFirehoseClient.listDeliveryStreams(com.amazonaws.services.kinesisfirehose.model.ListDeliveryStreamsRequest)"]],
 :name list-delivery-streams,
 :ns #namespace[amazonica.aws.kinesisfirehose],
 :arglists
 ([] [creds] [creds limit] [creds limit exclusive-start-delivery-stream-name]),
 :doc "Lists available firehose streams."}
```

Since this may only happen with some versions of the Java SDK, I tried this with `[com.amazonaws/aws-java-sdk "1.11.98" :exclusions [joda-time]]`.

**Comment by mcohen01** [comment]
this one is strange...i looked for a bit just now...if you just print the args inside of `intern-function` you'll see `list-delivery-streams` has different values than any other function that you would invoke by passing an empty map as the sole argument. not sure what's going on there....

**Comment by mcohen01** [comment]
fucking hell. no, i didn't see that lol. so there's the problem...

**Comment by mcohen01** [comment]
that code is just not correctly handling the case where you don't pass any explicit credentials in the function invocation. basically, there has to be a conditional that checks if credentials were passed in, something like in glacier.clj, and you invoke either `f` or `(partial f cred)`

**Comment by mcohen01** [comment]
he did it [here](https://github.com/mcohen01/amazonica/commit/aa129468ae5c20f5cdbc1ead86d5ef86d020ed62) but not in the fn above...

**Comment by mcohen01** [comment]
https://github.com/mcohen01/amazonica/pull/276 ?

**Comment by mcohen01** [comment]
`0.3.89` is on clojars

**Comment by lvh** [comment]
Will retest.

**Comment by lvh** [comment]
```
> (#'amazonica.aws.kinesisfirehose/list-delivery-streams {})
{:delivery-stream-names [], :has-more-delivery-streams false}
> (#'amazonica.aws.kinesisfirehose/list-delivery-streams)
{:delivery-stream-names (), :has-more-delivery-streams false}
```

🎂

**Comment by lvh** [comment]
Thanks a bunch!
