### ISSUE TITLE
Can't get S3 deleteObjects to work

### ISSUE THREAD

**Issue by eentzel** [mcohen01/amazonica#28]
I'm having trouble getting `delete-objects` to work. For `delete-object` (singular), the following seems to work:

``` clojure
(delete-object {:bucket-name "my-bucket" :key "key1"})
```

So by analogy between [DeleteObjectRequest](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/DeleteObjectRequest.html) and [DeleteObjectsRequest](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/DeleteObjectsRequest.html), I expected this to work:

``` clojure
(delete-objects {:bucket-name "my-bucket" :keys ["key1" "key2"]})
```

but instead I get:

```
UnsupportedOperationException: nth not supported on this type: Character
    at clojure.lang.RT.nthFrom(RT.java:857)
```

Am I wrong to expect `delete-objects` to work this way?

**Comment by glenthomas** [comment]
Can an example be added to the readme please?
