### ISSUE TITLE
Support DynamoDB TTL feature

### ISSUE THREAD

**Issue by brabster** [mcohen01/amazonica#284]
New AWS feature: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/TTL.html

Supported in SDK .108 as updateTimeToLive

http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/AmazonDynamoDBClient.html#updateTimeToLive-com.amazonaws.services.dynamodbv2.model.UpdateTimeToLiveRequest-

Can't see this as a var in the `amazonica.aws.dynamodbv2` namespace at runtime. Don't think we'll need to add anything to the item-related calls

**Comment by mcohen01** [comment]
`0.3.94` is on Clojars

**Comment by brabster** [comment]
There's a problem - amazon-kinesis-client also depends on an older version of aws-java-sdk-dynamodb, which overrides the newer version. Once I exclude that I can see the new function. Raised an issue on that over in the awslabs project.

**Comment by mcohen01** [comment]
`0.3.98` has updated deps. Not sure if that fixes this problem....
