### ISSUE TITLE
Why does Amazonica convert ByteBuffers via str?

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#295]
https://github.com/mcohen01/amazonica/blob/02410ec9c1a096365c90a566f20b2d643d7c6e41/src/amazonica/core.clj#L344

I assume this is just shorthand, but it's not immediately obvious to me that this is safe, since Strings are guaranteed to contain UTF16 code units, not arbitrary base64 garbage.

**Comment by mcohen01** [comment]
I think this was just a convenience when working with Kinesis or Dynamo. Clients should generally wrap their own byte array, but in the event they don't....

**Comment by lvh** [comment]
I just realized I misunderstood what does the conversion from base64 to ByteBuffer in the first place. Sorry!
