### ISSUE TITLE
Invalid date format header 

### ISSUE THREAD

**Issue by bilus** [mcohen01/amazonica#297]
We're trying to use minio to speed up our tests and I got totally stuck. When trying to create a bucket, minio complains about "Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format.". Based on the go code, it's triggered when it's unable to parse `x-amz-date` and/or `date` request headers (https://github.com/minio/minio/blob/1c97dcb10a9836d39cc4f92d3142175b5133f329/cmd/generic-handlers.go#L211). Maybe that's some sort of a hint.

You can start minio using docker:

    docker run -p 9000:9000 minio/minio server /export    

Code that recreates the problem:

    (amazonica.aws.s3/create-bucket {:access-key "ACCESS_KEY" :secret-key "SECRET_KEY" :endpoint "http://127.0.0.1:9000"} "foobar")

Error:
> AmazonS3Exception Invalid date format header, expected to be in ISO8601, RFC1123 or RFC1123Z time format. (Service: Amazon S3; Status Code: 400; Error Code: MalformedDate; Request ID: 3L137)  com.amazonaws.http.AmazonHttpClient.handleErrorResponse (AmazonHttpClient.java:1160)

Stacktrace:
```
     AmazonHttpClient.java: 1160  com.amazonaws.http.AmazonHttpClient/handleErrorResponse
     AmazonHttpClient.java:  748  com.amazonaws.http.AmazonHttpClient/executeOneRequest
     AmazonHttpClient.java:  467  com.amazonaws.http.AmazonHttpClient/executeHelper
     AmazonHttpClient.java:  302  com.amazonaws.http.AmazonHttpClient/execute
       AmazonS3Client.java: 3674  com.amazonaws.services.s3.AmazonS3Client/invoke
       AmazonS3Client.java:  799  com.amazonaws.services.s3.AmazonS3Client/createBucket
       AmazonS3Client.java:  729  com.amazonaws.services.s3.AmazonS3Client/createBucket
NativeMethodAccessorImpl.java:   -2  sun.reflect.NativeMethodAccessorImpl/invoke0
NativeMethodAccessorImpl.java:   62  sun.reflect.NativeMethodAccessorImpl/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  498  java.lang.reflect.Method/invoke
                       nil:   -1  sun.reflect.GeneratedMethodAccessor45/invoke
DelegatingMethodAccessorImpl.java:   43  sun.reflect.DelegatingMethodAccessorImpl/invoke
               Method.java:  498  java.lang.reflect.Method/invoke
            Reflector.java:   93  clojure.lang.Reflector/invokeMatchingMethod
            Reflector.java:   28  clojure.lang.Reflector/invokeInstanceMethod
                  core.clj:  783  amazonica.core/fn-call/fn
                  core.clj:  854  amazonica.core/intern-function/fn
               RestFn.java:  421  clojure.lang.RestFn/invoke
```

> Note: `(amazonica.aws.s3/set-s3client-options :path-style-access true)` doesn't help.

**Comment by vonrosen** [comment]
I am getting the same error. Was this closed because it is not reproducible?

**Comment by mcohen01** [comment]
`0.3.102` should work. tested with:

`(s3/create-bucket {:access-key "EZ2UBJY3XQBM1XI7PP3P" :secret-key "GzCV7A9GDFmv+MynL9H+lxBJ8bogus" :endpoint "http://127.0.0.1:9000"} "foobar")`

**Comment by pabielicki** [comment]
I resloved this by simply update amazonica to latest version :) 
This error is caused probably by outdated aws-java-sdk.
