### ISSUE TITLE
how to set content disposition in s3? 

### ISSUE THREAD

**Issue by jdkealy** [mcohen01/amazonica#302]
I see .setContentDisposition as a method being called in s3.clj but unsure how to to trigger this call.

**Comment by jdkealy** [comment]
Also Amazon says it has some way of setting the content-disposition in the response headers. 

It says you can do this: 

response-content-disposition=attachment

but just jamming it in the URL will return the error "Request specific response headers cannot be used for anonymous GET requests." 

As for generating-presigned-url's, the method does not seem to take any parameters to set those values. I see the parameters are 
credentials, bucket, key, optional-http-method. 

So how are you supposed to make a file downloadable?

**Comment by jdkealy** [comment]
The Ruby SDK has you do it like this: 
```

s3 = Aws::S3::Resource.new
obj = s3.bucket('aws-sdk').object('key')
obj.presigned_url(:get, response_content_disposition: '...')
#=> "https://aws-sdk.s3.amazonaws.com/key?response-content-disposition=..."
```

**Comment by mcohen01** [comment]
something like...
```clj
(put-object :bucket-name bucket1
            :key "stream"
            :input-stream input-stream
            :metadata {:content-disposition "attachment"}
            :return-values "ALL_OLD")
```

**Comment by jdkealy** [comment]
Wouldn't that requite that I'm uploading a new file?

**Comment by mcohen01** [comment]
Uh, ok, I don't really know what you're trying to do. If it's generate a url, something like

```clj
(generate-presigned-url :bucket-name "aws-sdk"
                        :key "key"
                        :content-type "application/octet-stream"
                        :response-headers {
                          :content-disposition "attachment"
                        })
```

**Comment by jdkealy** [comment]
Thanks! 
This ended up working for me: 
```

(defn file-path [_key]
  (str (s3/generate-presigned-url cred
                                  {:bucket-name bucket
                                   :key _key
                                   :method "GET"
                                   :response-headers {:content-disposition "attachment"}}
                                  (-> 6 hours from-now))))
```
