### ISSUE TITLE
Issues with clientconfig functions

### ISSUE THREAD

**Issue by bensnoozled** [mcohen01/amazonica#311]
Since commit https://github.com/mcohen01/amazonica/commit/ba1a42517f97e2c5d408ee1a2ef03d61ea8f3c84
I have been having an issue with Amazonica crashing in my project. I have deduced that the problem is encryption-client-fn and amazon-client-fn are not being set before the candidate function is called in core.clj. I was able to solve the problem by calling this code before executing an Amazonica function:

`
(amazonica.core/defclientconfig {:encryption-client-fn (memoize amazonica.core/encryption-client*)
                                 :amazon-client-fn (memoize amazonica.core/amazon-client*)}))
`

Is there a better/easier way to do this? Thanks in advance for any advice and thanks for Amazonica!

**Comment by mcohen01** [comment]
Hmm....looking at the code in core.clj I'm not sure how exactly you're running into this issue...

**Comment by mcohen01** [comment]
can you try with the latest version?

**Comment by bensnoozled** [comment]
Upgraded to "0.3.100" and gave it a try.  Sadly it did not fix the issue and is still crashing at the same point.

**Comment by mcohen01** [comment]
Can you provide steps to reproduce?

**Comment by mcohen01** [comment]
Can you provide steps to reproduce?

**Comment by bensnoozled** [comment]
Many thanks for following up on this. 
I created a new empty project with nothing but Amazonica to test. Here is the code I ran and results:

`(def cred {:access-key "KEY"
                  :secret-key "KEY"
                  :endpoint "us-east-1"})
`
then
`(sns/publish cred
        :topic-arn "ARN"
        :subject "subject"
        :message "message"
        :message-attributes {"attr" "value"}])`
which results in: 
`ClassCastException com.amazonaws.auth.BasicAWSCredentials cannot be cast to com.amazonaws.auth.AWSCredentialsProvider  amazonica.core/build-client (core.clj:148)`

In my actual project, credentials are always either passed by a direct map or with this method:
`(defn get-credentials
  []
  (let [access-key (-> (cfg/get :aws) :access-key)
        secret-key (-> (cfg/get :aws) :secret-key)]
    (if
        (every? #(not (nil? %)) [access-key secret-key]) {:access-key access-key
                                                          :secret-key secret-key}
        (InstanceProfileCredentialsProvider. ))))
`
The result is the same no matter the method I use.

**Comment by mcohen01** [comment]
can you try with `0.3.101`?

**Comment by bensnoozled** [comment]
That fixed it. Thanks again!

**Comment by mcohen01** [comment]
👍
