### ISSUE TITLE
Can't use set-s3client-options with DefaultAWSCredentialsProviderChain.

### ISSUE THREAD

**Issue by austinhaas** [mcohen01/amazonica#315]
```
(ns s3-test.core
  (:require
   [amazonica.aws.s3 :as s3])
  (:gen-class))

(s3/set-s3client-options :set-max-connections 50)

(defn -main
  "I don't do a whole lot ... yet."
  [& args]
  (println "Hello, World!"))
```

```
lein run
```

```
java.lang.UnsupportedOperationException: Client is immutable when created with the builder.
```

**Comment by mcohen01** [comment]
Yeah, sorry, I think in the latest release you have to pass the client config as an explicit map as the first arg to any S3 functions. So something like:

`(s3/get-object {:client-config {:max-connections 50}} :bucket-name "foo" :key "bar")`

**Comment by austinhaas** [comment]
Thanks for the reply. That doesn't seem to have any effect, though. I can set the value to much higher than my total connections and it will still time out waiting for a connection from the pool. And it doesn't appear to be making more connections than the default. I don't know any other way to verify if this setting is having any effect.

**Comment by mcohen01** [comment]
The [`ClientConfiguration`](https://github.com/aws/aws-sdk-java/blob/master/aws-java-sdk-core/src/main/java/com/amazonaws/ClientConfiguration.java) gets set on the client. You can set other options and see them logged to the console. For instance, you can try setting a proxy host, see it logged to the console, and of course fail to connect to the (nonexistent) proxy. 

```
(s3/get-object 
  {:client-config 
    {:max-connections 50
     :proxy-host "http://localhost"
     :proxy-port 90001}}
  :bucket-name "foo" :key "bar")
```
