### ISSUE TITLE
Latest version does not allow for a local endpoint

### ISSUE THREAD

**Issue by cvkline** [mcohen01/amazonica#316]
I was using 0.3.22 with success, and then came forward to 0.3.101, and now I'm experiencing an issue that's preventing me from connecting to a local instance of DynamoDB.

If I specify `http://localhost:8000` as my `:endpoint`, it throws a "com.amazonaws.SdkClientException: Unable to load region information from any provider in the chain" error.

But specifying a region either in my AWS client configuration or via environment variables causes Amazonica to completely ignore my endpoint specification and attempt to connect to that real live AWS region.

**Comment by mcohen01** [comment]
`0.3.102` was released yesterday with [this fix](https://github.com/mcohen01/amazonica/commit/994029ad5cd2dfc8fe257d4e82d989a75c7ce777) which might be the fix you're looking for.

**Comment by cvkline** [comment]
Confirmed, that fixed it. Just my bad luck to upgrade when I did, I guess.   Thank you!

**Comment by mcohen01** [comment]
👍
