### ISSUE TITLE
Need to be able to specify builder options

### ISSUE THREAD

**Issue by rwstauner** [mcohen01/amazonica#320]
I've looked at several past issues regarding client-config and path-style-access but nothing seems to be working for me on the latest version.

Is it possible to set path-style-access for s3?
Neither `set-s3client-options` nor `:client-config` seem to have any effect for me.
Browsing the java docs it looks like i need to call something on the builder but i'm not sure how to get access to that.

Any thoughts?

**Comment by rwstauner** [comment]
Clarification: as mentioned in #315 i think `set-s3client-options` doesn't work anymore
(i get `UnsupportedOperationException Client is immutable when created with the builder.  com.amazonaws.AmazonWebServiceClient.checkMutability (AmazonWebServiceClient.java:854)`)
but i haven't been able to get client-config to do anything...
i can get the proxy-host/port thing to work, but it doesn't seem like the path-style-access is being utilized.

**Comment by rwstauner** [comment]
I get the same "immutable" error with this monstrosity
```clojure
  (doto (amazonica.core/amazon-client*
          (Class/forName "com.amazonaws.services.s3.AmazonS3Client")
          s3/default-creds
          {})
    (.setS3ClientOptions (doto (com.amazonaws.services.s3.S3ClientOptions.)
                           (.setPathStyleAccess true)))))
```
so it really seems like i need to call the method on the builder :-/

**Comment by rwstauner** [comment]
i can get it to work with this
```clojure
(do
  (require 'amazonica.core)
  (in-ns 'amazonica.core)
  (defn enable-path-style-access
    [builder]
    (if (instance? com.amazonaws.services.s3.AmazonS3ClientBuilder builder)
      (.enablePathStyleAccess builder)
      builder))
  (alter-var-root (var builder) (partial comp enable-path-style-access)))
```

**Comment by mcohen01** [comment]
In `0.3.104` you should be to pass S3 Client Options under the `client-config` key like so:

```
(s3/list-buckets
  {:client-config {
    :path-style-access-enabled false
    :chunked-encoding-disabled false
    :accelerate-mode-enabled false
    :payload-signing-enabled true
    :dualstack-enabled true
    :force-global-bucket-access-enabled true}})
```

**Comment by rwstauner** [comment]
Awesome! Thanks!
