### ISSUE TITLE
Add support for AwsSkdMetrics

### ISSUE THREAD

**Issue by jwhitlark** [mcohen01/amazonica#329]
Requires com.amazonaws/aws-java-sdk-cloudwatchmetrics

The following almost works, but I can't get it to honor the region, (probably something to do with the credential provider).

    (com.amazonaws.metrics.AwsSdkMetrics/enableDefaultMetrics)
    (com.amazonaws.metrics.AwsSdkMetrics/setCredentialProvider nil)
    (com.amazonaws.metrics.AwsSdkMetrics/setRegion "us-west-2")
    (com.amazonaws.metrics.AwsSdkMetrics/setMetricNameSpace "myHappyMetrics")
  
    ;; The following should stop collection
    (com.amazonaws.metrics.AwsSdkMetrics/disableMetrics))

This is the article that lead me to this package: https://aws.amazon.com/blogs/developer/tuning-the-aws-sdk-for-java-to-improve-resiliency/

Here is the javadoc for the package: http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/metrics/package-summary.html

**Comment by mcohen01** [comment]
`0.3.108` is on clojars. It has the latest Java SDK, which is required for us-west-2 region.

**Comment by jwhitlark** [comment]
No, this was for us-west-2.  Turns out the problem I was having is you need to set the region before enabling the metrics, unlike the credentials. 

Do you think this could use a clj namespace?  It's been a long time since I've looked at the amazonica internals, and I'm not sure how much benefit would be added.

**Comment by jwhitlark** [comment]
Too old.
