### ISSUE TITLE
elbv2 describe-load-balancers doesn't work

### ISSUE THREAD

**Issue by SevereOverfl0w** [mcohen01/amazonica#337]
Similar to #306 

`(elbv2/describe-load-balancers {:endpoint "eu-west-1"})` doesn't work, workaround is `(elbv2/describe-load-balancers {:endpoint "eu-west-1"} {:this-makes "it-work"})` as taken from above issue.

**Comment by SevereOverfl0w** [comment]
`elbv2/describe-target-groups` also has this issue.

**Comment by mcohen01** [comment]
technically, the call would be something like:
```
(elbv2/describe-load-balancers
  {:endpoint "eu-west-1"}
  {:names ["elb1" "elb2"]})
``` 
as there is no no-arg version of [`describeLoadBalancers`](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/elasticloadbalancingv2/AmazonElasticLoadBalancingClient.html#describeLoadBalancers-com.amazonaws.services.elasticloadbalancingv2.model.DescribeLoadBalancersRequest-). It just happens that none of the properties of `DescribeLoadBalancersRequest` are required, so if you're not passing any you still would need to pass an empty map, `(elbv2/describe-load-balancers {:endpoint "eu-west-1"} {})`.
