### ISSUE TITLE
SQS/SNS Subscribe queue to topic with permissions

### ISSUE THREAD

**Issue by lasiltan** [mcohen01/amazonica#344]
I'm struggling to route messages from a topic to a queue.

I can create the topic and queue. I can subscribe the queue to the topic. But for messages to actually get sent from the topic to the queue, the queue must allow the topic to write to it.

So I need to add a permission to the queue as per http://docs.aws.amazon.com/sns/latest/dg/SendMessageToSQS.html#SendMessageToSQS.sqs.permissions

How do I do this with amazonica?

**Comment by mcohen01** [comment]
>To set a policy on a queue, you can use the Amazon SQS console or the SetQueueAttributes API [1] action. Before you start, make sure you have the ARN for the topic that you want to allow to send messages to the queue.  [2]

I suspect you can pass your policy as a string of json. See the [IdentityManagement example](https://github.com/mcohen01/amazonica#identitymanagement) for inspiration.

[1] http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_SetQueueAttributes.html
[2] http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/sqs/AmazonSQSClient.html#setQueueAttributes-com.amazonaws.services.sqs.model.SetQueueAttributesRequest-

**Comment by lasiltan** [comment]
Thanks! Got it working by setting the correct permissions in the AWS Management Console and then doing a `sqs/get-queue-attributes` for an example.

**Comment by mcohen01** [comment]
👍
