### ISSUE TITLE
No way to specify both endpoint and signing region [for Minio]?

### ISSUE THREAD

**Issue by metametadata** [mcohen01/amazonica#346]
I'm trying to port [this](https://docs.minio.io/docs/how-to-use-aws-sdk-for-java-with-minio-server) `Java SDK` example for `Minio` to `amazonica` and do smt. like this:

```clj
(def credentials {:access-key    "..."
                  :secret-key    "..."
                  :endpoint      "http://localhost:9000"
                  :client-config {:path-style-access-enabled true}})
(s3/list-objects credentials {:bucket-name "mybucket"})
```

It fails with error from `Minio`:

```
com.amazonaws.services.s3.model.AmazonS3Exception: Region does not match. (Service: Amazon S3; Status Code: 400; Error Code: InvalidRegion; Request ID: 3L137; S3 Extended Request ID: 3L137)
```

I'm really not sure but I suspect that the problem is that I don't specify the region as in the original Java example:

```java
AwsClientBuilder.EndpointConfiguration("http://localhost:9000", Regions.US_EAST_1.name()))
```

How would I pass `Regions.US_EAST_1.name()` value to `amazonica`? It looks like this ([`signingRegion`](docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/client/builder/AwsClientBuilder.EndpointConfiguration.html)) argument [is always set to `nil` by amazonica](https://github.com/mcohen01/amazonica/blob/ce191a46b9b02da7af3570a9d8daa7cd37418576/src/amazonica/core.clj#L160).

**Comment by metametadata** [comment]
The suspicion seems to be true. Because my code snippet starts working if I change [`amazonica` implementation](https://github.com/mcohen01/amazonica/blob/ce191a46b9b02da7af3570a9d8daa7cd37418576/src/amazonica/core.clj#L160) from:

```clj
(AwsClientBuilder$EndpointConfiguration. endpoint nil))
```

to:

```clj
(AwsClientBuilder$EndpointConfiguration. endpoint "us-east-1")
; MINIO_REGION is also set to "us-east-1"
```

**Comment by metametadata** [comment]
For now I settled with the workaround: not specifying `MINIO_REGION` at all.

**Comment by coelias** [comment]
This problem affects localstack (sqs) as well, where you need to specify both endpoint and signingRegion, then I realised that I always was getting `us-east-1` in my requests. Env vars had no effect whatsoever.
 
I looked into aws-java-sdk:
https://github.com/aws/aws-sdk-java/blob/382df578fbced92d36756be2a511f02d5f932cd8/aws-java-sdk-core/src/main/java/com/amazonaws/util/AwsHostNameUtils.java#L58

`If region is null, then endpoint is totally non-standard; guess us-east-1 for lack of a better option.`

Signing Region is a parameter that should be part of credentials.

**Comment by Limess** [comment]
We're also running into this issue with SQS and newer versions of localstack (>0.12.x) with proper multi-region support.

I also tried following the aws-sdk-java code through, but wasn't confident exactly what would be set as the V4 signing region if it wasn't specified. If setting this does fix the issue, would a sensible change be to instead set it to `AWS_DEFAULT_REGION`, rather than `null`, to at least allow some outside control of this?
