### ISSUE TITLE
Options for smaller Jar

### ISSUE THREAD

**Issue by eigenhombre** [mcohen01/amazonica#347]
`amazonica` currently needs the entire AWS Java SDK, which is very large (too large, in fact, to fit inside the AWS Lambda 50MB maximum zip/jar file requirements).

I'm guessing many projects only need two or three AWS services.  For these, and for the above use case, it would be nice to only include the parts you actually need.  My short-term solution is to make a fork of Amazonica, locally installed, which removes all the unneeded parts, but this is obviously a horrible hack.

I'm not sure how to modularize things so you don't need to "eat the whole pie," so to speak.  But it would be great for anyone trying to write Clojure lambdas that use Amazonica (until [Portkey](https://github.com/portkey-cloud/portkey) is actually a thing, perhaps).

**Comment by mcohen01** [comment]
Can't you just exclude `com.amazonaws/aws-java-sdk` and then add back in only those services you depend on?

**Comment by eigenhombre** [comment]
Duh. That worked great. Thanks for the suggestion. Closing ticket. Thanks again.
