### ISSUE TITLE
Impossible execute minimal snippet code related to SQS.

### ISSUE THREAD

**Issue by Afsoon** [mcohen01/amazonica#349]
Hi.

In our project we tried to use the last version the Amazonica, with `localstack`, but we found problems trying to connect to AWS. Each time we tried to list all queues from AWS, we get the following error each time we list with `list-queues` from AWS:

``` clojure
(require '[amazonica.aws.sqs :as aws])
=> nil
(aws/list-queues)
NoSuchMethodError com.fasterxml.jackson.databind.ObjectMapper.enable([Lcom/fasterxml/jackson/core/JsonParser$Feature;)Lcom/fasterxml/jackson/databind/ObjectMapper;  com.amazonaws.partitions.PartitionsLoader.<clinit> (PartitionsLoader.java:54)
```

In case we tried with localstack, it works.

``` clojure
(require '[amazonica.aws.sqs :as aws])
=> nil
(aws/list-queues {:endpoint "http://localhost:4576"})
=> {:queue-urls []}
```

We detected this error start happen after version 0.3.100, included, that is related to the PR #299 

https://github.com/mcohen01/amazonica/commit/d961fce8967ebfd7127e9c4bbce2e5e5acc7a8d8#diff-0fff143854a4f5c0469a3819b978a483

**Comment by mcohen01** [comment]
Looks like a `jackson` dependency problem. I'd look at your dependency tree to see if you can exclude it from someplace.

**Comment by Afsoon** [comment]
I tried to follow the suggestion from `lein deps :tree` and nothing. And I am not sure can be a Jackson problem, because I tried the first snippet code with amazonica version 0.3.99 and it works, I could list all my queues from AWS.

**Comment by mcohen01** [comment]
If you create a new project from scratch, and include the latest amazonica as the only dependency, do you see the same error?

**Comment by Afsoon** [comment]
I made what do you say and it's working. So then we have to look which dependencies is the problem. We have a couple the dependencies that have jackson as transitive. 

Thank you for the help.

**Comment by mcohen01** [comment]
👍
