### ISSUE TITLE
Exposed package-visible fns

### ISSUE THREAD

**Issue by lvh** [mcohen01/amazonica#350]
Looks like I didn't quite kill this one dead last time. Lots of `#'amazonica.aws.SERVICE/execute-OPERATION`. These are all intended to be internal: they're certainly not marked public, and generally annotated with `@SdkInternal`.

Would you take a PR that addresses this?

**Comment by mcohen01** [comment]
fire when ready

**Comment by lvh** [comment]
@mcohen01 I dunno if you saw that in the PR: but the tests fail for me on master before and after this PR.

**Comment by mcohen01** [comment]
yeah, the tests you have to run individually, and often with some slight modifications. don't really have time to fix that atm :(
