### ISSUE TITLE
SNS gives error with PartitionsLoader NoClassDefFound

### ISSUE THREAD

**Issue by staypufd** [mcohen01/amazonica#355]
When trying the code below from the SNS section in a REPL, I get the following error:

NoClassDefFoundError Could not initialize class com.amazonaws.partitions.PartitionsLoader  com.amazonaws.regions.RegionMetadataFactory.create (RegionMetadataFactory.java:30)

I am using the latest JDK 8 on latest Mac OS X Sierra.
I am also using Leiningen latest release with Clojure 1.8.2.
I used the (defcredential) to set my creds.

`(def topic-name (.. (java.util.UUID/randomUUID) toString))

(let [topic (:topic-arn (create-topic :name topic-name))]

  (clojure.pprint/pprint (list-topics))

  
  
  (subscribe :protocol "http"
             :topic-arn topic
             :endpoint "http://www.example.com")

  (clojure.pprint/pprint (list-subscriptions))

  (publish :topic-arn topic
           :subject "test"
           :message (str "Todays is " (java.util.Date.)))

  (delete-topic :topic-arn topic))
=> #'user/topic-name
NoClassDefFoundError Could not initialize class com.amazonaws.partitions.PartitionsLoader  com.amazonaws.regions.RegionMetadataFactory.create (RegionMetadataFactory.java:30)
`

I also tried to build up a simple call like so
`(-> (AmazonSNSClientBuilder/standard)
    (.withRegion (Regions/US_EAST_1))
    (.build))
NoClassDefFoundError Could not initialize class com.amazonaws.partitions.PartitionsLoader  com.amazonaws.regions.RegionMetadataFactory.create (RegionMetadataFactory.java:30)
`

and as you can see I get the same error.

Any help or guidance is appreciated,

Sam Griffith

**Comment by mcohen01** [comment]
can't reproduce with:

```
user=> (require '[amazonica.aws.sns :as sns])
nil

user=> (def topic-name (.. (java.util.UUID/randomUUID) toString))
#'user/topic-name

user=> (def topic (:topic-arn (sns/create-topic :name topic-name)))
#'user/topic

user=> (sns/list-topics)
{:topics [{:topic-arn "arn:aws:sns:us-east-1:122456782112:02cb01cf-04f5-4596-928f-933cdc6477ea"} {:topic-arn "arn:aws:sns:us-east-1:122456782112:NotifyMe"} {:topic-arn "arn:aws:sns:us-east-1:122456782112:PupuSES"} {:topic-arn "arn:aws:sns:us-east-1:122456782112:config-topic"} {:topic-arn "arn:aws:sns:us-east-1:122456782112:dynamodb"}]}

user=> (sns/subscribe :protocol "http" :topic-arn topic :endpoint "http://www.example.com")
{:subscription-arn "pending confirmation"}

user=> (sns/list-subscriptions)
{:next-token "AAGBC7lMBNogo6H1eALkFktCyXJNIr4a6+wpoch1anq46g==", :subscriptions [{:protocol "email", :endpoint "mc@gmail.com", :owner "122456782112", :topic-arn "arn:aws:sns:us-east-1:122456782112:dynamodb", :subscription-arn "arn:aws:sns:us-east-1:122456782112:dynamodb:58e096af-3d98-4a94-86f2-47c122a44252"} {:protocol "http", :endpoint "http://pupuserio.us/sns-notification", :owner "122456782112", :topic-arn "arn:aws:sns:us-east-1:122456782112:PupuSES", :subscription-arn "arn:aws:sns:us-east-1:122456782112:PupuSES:6c804c87-1fff-4865-8d90-e22a70871ec1"} {:protocol "email", :endpoint "mc@gmail.com", :owner "122456782112", :topic-arn "arn:aws:sns:us-east-1:122456782112:my-topic", :subscription-arn "arn:aws:sns:us-east-1:122456782112:my-topic:94d45da1-b288-4091-bacf-663251d375bd"} {:protocol "email", :endpoint "mc@gmail.com", :owner "122456782112", :topic-arn "arn:aws:sns:us-east-1:122456782112:NotifyMe", :subscription-arn "arn:aws:sns:us-east-1:122456782112:NotifyMe:98f10c0b-289c-424f-ac28-872144528eba"} {:protocol "http", :endpoint "http://www.example.com", :owner "122456782112", :topic-arn "arn:aws:sns:us-east-1:122456782112:02cb01cf-04f5-4596-928f-933cdc6477ea", :subscription-arn "PendingConfirmation"}]}

user=> (sns/publish :topic-arn topic :subject "test" :message (str "Todays is " (java.util.Date.)))
{:message-id "d5bf4b57-63d8-59cc-b79b-19f90899991d"}

user=> (sns/delete-topic :topic-arn topic)
{}
```
