### ISSUE TITLE
show-functions name collision when I tried an example from the S3 section in docs

### ISSUE THREAD

**Issue by jrbrodie77** [mcohen01/amazonica#356]
I'm trying to follow the readme using Cursive.  When I use

`(ns my.core
    (:use [amazonica.aws.s3]
             [amazonica.aws.s3transfer]))`

I get a collision between 'show-functions' functions and an error in the REPL, using Cursive/Lein.

I'm a clojure newb, but if anyone is willing to explain why this isn't or is a problem, let me know!  I did manage to make it work by replacing the :use by a :require with aliases.

**Comment by mcohen01** [comment]
Well, you can blame this on either one, amazonica or `:use`. Generally though I think Clojure people discourage `:use`.

**Comment by jrbrodie77** [comment]
It's in your docs though:  https://github.com/mcohen01/amazonica#s3

**Comment by jrbrodie77** [comment]
But thanks for the library, very comprehensive!

**Comment by mcohen01** [comment]
>It's in your docs though: https://github.com/mcohen01/amazonica#s3

Yes, that's a good point. :-) Good Clojurians would frown on that. I probably did that....I don't know, to isolate the function names for each of those services. I would like to think I would namespace everything in production code.
