### ISSUE TITLE
S3 client get-object-acl(String, String, CannedAccessControlList) does not work

### ISSUE THREAD

**Issue by acrao** [mcohen01/amazonica#37]
I'm trying to invoke the following AmazonS3Client method : 

http://amzn.to/1hDfA05

```
public void setObjectAcl(String bucketName, String key,CannedAccessControlList acl)
```

Here is how I'm invoking it in my code (where creds is a  map with my aws credentials and client config): 

```
(require '[amazonica.aws.s3 :as amazonica-s3])
(import com.amazonaws.services.s3.model.CannedAccessControlList)
(amazonica-s3/set-object-acl creds "com.test.bucket" "test/key" CannedAccessControlList/PublicRead)

IllegalArgumentException Don't know how to create ISeq from: com.amazonaws.services.s3.model.CannedAccessControlList  clojure.lang.RT.seqFrom (RT.java:494)
```

I have a feeling that its trying to invoke a similar method in the s3 client with the following signature instead: 

```
public void setObjectAcl(String bucketName, String key, AccessControlList acl)
```

Does amazonica API match the underlying client API by type of args or just the count of the args?

**Comment by deepakjangid123** [comment]
User is providing me => :access-key : string format, :secret-key : string format, :bucket-name : string format and  :zone : string format
So how can I get file-content from S3 bucket.
