### ISSUE TITLE
Support for ParameterStore / AWSSimpleSystemsManagement?

### ISSUE THREAD

**Issue by claj** [mcohen01/amazonica#370]
The new cool kid on the block for storing secrets in AWS seems to be the Parameter Store, which seems to be called AWS Systems Manager or `AWSSimpleSystemsManagement`.

There are some sparse usage docs at the Stackoverflow question [Accessing AWS parameter store values with custom KMS key
](https://stackoverflow.com/questions/43211121/accessing-aws-parameter-store-values-with-custom-kms-key).

Should I simply try to add support for this API?

**Comment by claj** [comment]
oh, thanks! Then I add it to the README when I have some working example.

**Comment by bcambel** [comment]
Hi guys @mcohen01 @claj , 
The Java client expects a GetParameterRequest instance which I initialise as follows 
```
(def gpr (new GetParameterRequest))
(.withName gpr "mysql-rds-conn")
(get-request gpr)
```
throws an 
``` :cause "Don't know how to create ISeq from: com.amazonaws.services.simplesystemsmanagement.model.GetParameterRequest"
```
Any idea what I am doing wrong ? 

Thanks

**Comment by mcohen01** [comment]
Why are you using raw Java?

```
(require '[amazonica.aws.simplesystemsmanagement :as ssm])
(ssm/get-parameter :name "mysql-rds-conn")
```

**Comment by mlimotte** [comment]
See also [Amazon Secrets Manager](https://aws.amazon.com/secrets-manager/).  Which is kind of like parameter store integrated with KMS; plus custom key rotation via lambdas.

**Comment by b2berry** [comment]
+1 for SWS Secrets Manager
