### ISSUE TITLE
SQS: cleanly make :attributes required

### ISSUE THREAD

**Issue by vemv** [mcohen01/amazonica#372]
If I invoke `(sqs/create-queue :queue-name "cljtest")` (that is, without `:attributes {}` params), I will get the following error:

`ClassCastException sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to java.lang.Class  clojure.core/instance?--5126 (core.clj:144)`

...that seems overly obscure for such a trivial issue. Perhaps this kind of options could be validated with a simple `:pre` condition (or similiar)?

Thanks - Victor

**Comment by mcohen01** [comment]
It's a bug, `attributes` aren't required. You should be able to call it with `(sqs/create-queue :queue-name "cljtest")`

`0.3.127` is on clojars

**Comment by vemv** [comment]
Fantastic, thank you @mcohen01!
