### ISSUE TITLE
amazonica.aws.cloudwatch/get-metric-data is missing

### ISSUE THREAD

**Issue by lischenko** [mcohen01/amazonica#376]
Perhaps I am missing something, but I can't find a way to call CloudWatch `get-metric-data`:

    > (clojure.pprint/pprint (ns-publics 'amazonica.aws.cloudwatch))
    {get-metric-statistics
     #'amazonica.aws.cloudwatch/get-metric-statistics,
     list-metrics #'amazonica.aws.cloudwatch/list-metrics,
     shutdown #'amazonica.aws.cloudwatch/shutdown,
     delete-dashboards #'amazonica.aws.cloudwatch/delete-dashboards,
     show-functions #'amazonica.aws.cloudwatch/show-functions,
     delete-alarms #'amazonica.aws.cloudwatch/delete-alarms,
     waiters #'amazonica.aws.cloudwatch/waiters,
     disable-alarm-actions
     #'amazonica.aws.cloudwatch/disable-alarm-actions,
     enable-alarm-actions #'amazonica.aws.cloudwatch/enable-alarm-actions,
     list-dashboards #'amazonica.aws.cloudwatch/list-dashboards,
     set-alarm-state #'amazonica.aws.cloudwatch/set-alarm-state,
     describe-alarms-for-metric
     #'amazonica.aws.cloudwatch/describe-alarms-for-metric,
     put-metric-data #'amazonica.aws.cloudwatch/put-metric-data,
     describe-alarms #'amazonica.aws.cloudwatch/describe-alarms,
     describe-alarm-history
     #'amazonica.aws.cloudwatch/describe-alarm-history,
     put-metric-alarm #'amazonica.aws.cloudwatch/put-metric-alarm,
     get-cached-response-metadata
     #'amazonica.aws.cloudwatch/get-cached-response-metadata,
     put-dashboard #'amazonica.aws.cloudwatch/put-dashboard,
     get-dashboard #'amazonica.aws.cloudwatch/get-dashboard,
     client-class #'amazonica.aws.cloudwatch/client-class}
    nil

I am using `[amazonica "0.3.127"]` and I would expect it to reflect the operation from the java SDK: https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/cloudwatch/AmazonCloudWatch.html#getMetricData-com.amazonaws.services.cloudwatch.model.GetMetricDataRequest-

**Comment by mcohen01** [comment]
Needed the latest Java SDK for access to that method. `0.3.128` is on clojars

**Comment by lischenko** [comment]
Thanks, it works. 

I was about to suggest updating the README but you beat me to it! Closing.
