### ISSUE TITLE
Support and document canned ACLs in s3 put-object

### ISSUE THREAD

**Issue by fiddlerwoaroof** [mcohen01/amazonica#379]
It's unclear whether amazonica supports canned ACLs when using s3 put-object, nor how you would specify such ACLs.

**Comment by mcohen01** [comment]
should be something like `(s3/put-object :bucket-name "foo" :key "bar" :canned-acl "PublicRead")`

**Comment by fiddlerwoaroof** [comment]
Thanks, that worked.

**Comment by tanzoniteblack** [comment]
Using amazonica 0.3.117 (aws SDK 1.11.237), I needed to set `:canned-acl` to `:public-read`, not `"PublicRead"`, for this to work.
