### ISSUE TITLE
Question: Set email headers with SES

### ISSUE THREAD

**Issue by yannvanhalewyn** [mcohen01/amazonica#386]
I'd like to set custom email headers when using `amazonica.aws.simpleemail/send-email`. Is that possible? I'm specifically interested in the `Reply-To, ` header. [AWS docs](https://docs.aws.amazon.com/ses/latest/DeveloperGuide/email-format.html)

Thanks for all the good work on the library!

**Comment by mcohen01** [comment]
should be something like `(send-email :reply-to-addresses ["me@gmail.com" "you@gmail.com"])`

**Comment by yannvanhalewyn** [comment]
Ah perfect thanks! Couldn't figure that out from the source code 🍾

**Comment by mcohen01** [comment]
Yeah, can't figure out much from looking at this source, gotta reference the [JavaDocs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html).
