### ISSUE TITLE
How to use amazonica with localstack 

### ISSUE THREAD

**Issue by abhi18av** [mcohen01/amazonica#387]
Hi @mcohen01 

First off, I'd like to say thank you for this wonderful library :)

I'd like to ask whether it's possible to use `amazonica` with `localstack` ( https://github.com/localstack/localstack ) to develop application with deployment to AWS in mind ? 

Please let me know how could I configure this to use with localstack.

**Comment by mcohen01** [comment]
I'm not familiar with localstack at all, but see https://github.com/mcohen01/amazonica/issues/342

maybe something like `(s3/list-objects {:endpoint "http://localhost:4572"} :bucket-name "foo")`

**Comment by abhi18av** [comment]
Ah yes, that worked. Thanks 👍
