### ISSUE TITLE
dynamodbstreams

### ISSUE THREAD

**Issue by aaronblenkush** [mcohen01/amazonica#393]
Where is the DynamoDB Streams API? https://docs.aws.amazon.com/cli/latest/reference/dynamodbstreams/index.html

**Comment by aaronblenkush** [comment]
I was able to get access to the DynamoDB Streams API by adding a new namespace with the following contents:
```clojure
(ns amazonica.aws.dynamodbstreams
  (:require [amazonica.core :as amz])
  (:import [com.amazonaws.services.dynamodbv2 AmazonDynamoDBStreamsClient]))
(amz/set-client AmazonDynamoDBStreamsClient *ns*)
```
Thanks, @mcohen01, for making this library so easy to update!

**Comment by mcohen01** [comment]
👍
