### ISSUE TITLE
Sending SQS messages to FIFO queues

### ISSUE THREAD

**Issue by smsharman** [mcohen01/amazonica#395]
Hi Michael,

Thanks for a library that I use a lot and which works really well for me. I have a question regarding the SQS client - when sending messages using FIFO queues, you must set a message parameter "MessageGroupId" to a non-blank value. 

According to https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/FIFO-queues-getting-started-java.html 

this is done by using the setMessageGroupId on the SendMessageRequest class created to deal with a specific message. Java interop is something I'm quite new to in Clojure, and using reflection doubly so. Is this something that can be done easily using the current Amazonica library, or does some specific additional code need to be written to cope with this case?

Many thanks for any advice.

-- Steve

**Comment by mcohen01** [comment]
something like `(sqs/send-message :queue-url "..." :message-body "..." :message-group-id "...")`

see the [docs](https://github.com/mcohen01/amazonica#documentation)

**Comment by smsharman** [comment]
Yes, that works perfectly, thank you. I'd tried something similar with :messageGroupId rather than message-group-id - that's the lesson for the future. Much appreciated.
