### ISSUE TITLE
aws-java-sdk-s3 not specified as required dependancy in the 'For the memory constrained' section 

### ISSUE THREAD

**Issue by Akeboshiwind** [mcohen01/amazonica#397]
I recently updated to the latest version (0.3.133) from 0.3.84 and have exclusions setup similar to how they're setup in the 'For the memory constrained' setup in the README file. I was surprised to find that I got a ClassNotFoundException and had to load the 'aws-java-sdk-s3' dependancy to get rid of the error.

It should probably be made clear in the documentation that 'aws-java-skk-s3' is a required dependancy if you are using exclusions.

**Comment by mcohen01** [comment]
This was a regression removing reflection warnings a while back. You shouldn't need the S3 jar with `0.3.134`.

**Comment by Akeboshiwind** [comment]
Awesome, that works perfectly.

Thank you :)
