### ISSUE TITLE
Reuse of session credentials can be improved

### ISSUE THREAD

**Issue by biiwide** [mcohen01/amazonica#399]
Recently I have been receiving the following exception in processes running in ECS:
```
com.amazonaws.auth.EC2ContainerCredentialsProviderWrapper@52132b36:
  Too Many Requests (Service: null; Status Code: 429; Error Code: null; Request ID: null)
```
It looks like the AWS service that provides session credentials to ECS tasks is rate limiting the requests.  The EC2ContainerCredentialsProviderWrapper does cache session credentials, but the cache is tied to the instance.

Updating `amazonica.core/get-credentials` to use the singleton instance returned by `(DefaultAWSCredentialsProviderChain/getInstance)` instead of constructing a new `DefaultAWSCredentialsProviderChain` on every call should reduce calls to the credentials service.

**Comment by mcohen01** [comment]
`0.3.136` is on clojars
