### ISSUE TITLE
Could not determine best method to invoke for upload-directory

### ISSUE THREAD

**Issue by surendrand** [mcohen01/amazonica#401]
I am trying to upload a directory using upload-directory function as
```

(s3-transfer/upload-directory :bucket-name bucket-name
                                :virtual-directory-key-prefix source-directory
                                :directory (io/file source-directory)
                                :include-subdirectories true)
  
```
I am getting an exception as follows 

```
Caused by: java.lang.IllegalArgumentException: Could not determine best method to invoke for upload-directory uSing arguments (:bucket-name "xyz" :virtual-directory-key-prefix "/tmp/download/" :directory #object[java.io.File 0x44a98a23 "/tmp/download"] :metadata {:content-type "text/json"} :include-subdirectories true)
	at amazonica.core$intern_function$fn__5773.doInvoke(core.clj:1034)
	at clojure.lang.RestFn.invoke(RestFn.java:805)
	at utils.s3$upload.invokeStatic(s3.clj:18)
```

I am referring uploadDirectory function from 
https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#uploadDirectory-java.lang.String-java.lang.String-java.io.File-boolean-
as a reference.

**Comment by mcohen01** [comment]
So when you're looking at the Javadocs (as you should) and the Java client method takes a single argument which is an Amazon *Request type bean (e.g. the [copy() method](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/transfer/TransferManager.html#copy-com.amazonaws.services.s3.model.CopyObjectRequest-) on the `TransferManager` which takes a `CopyObjectRequest`), then you pass a Clojure map or a map without curly brackets as you are in this case (I forget the name the Clojure community uses for that style). But some clients, notably the S3 and S3Transfer clients, contain methods that simply take any number of scalars, such as the method you're calling here, `uploadDirectory`. In these cases you simply pass the arguments, so your call would look like

```
(s3-transfer/upload-directory bucket-name source-directory (io/file source-directory) true)
```
