### ISSUE TITLE
Ability to create different instances of S3 TransferManager

### ISSUE THREAD

**Issue by iam-nagarajan** [mcohen01/amazonica#403]
S3 Transfer Manager creates ThreadPool internally when it is created. We need to invoke shutdown-now to clean up resources after usage.

AFAIK, amazonica.aws.s3transfer namespace uses a single instance of TransferManager. Once the shutdown-now is invoked on s3transfer, we will not be able to do any transfer using the functions exposed by amazonica.aws.s3transfer.

If there is ability to create instances of TransferManager we can cleanup resources without making the s3transfer unusable.

**Comment by mcohen01** [comment]
You can pass a `client-config` key in the optional credentials map to supply your own `TransferManager` with control over the thread pool and shutdown behavior.

`(s3/download {:client-config {:transfer-manager-fn (fn [_ _ _] (TransferManager.))}} "bucket" "key" (java.io.File. "/path/to/file"))`
