### ISSUE TITLE
Support custom config and credentials location

### ISSUE THREAD

**Issue by ChrisLane** [mcohen01/amazonica#408]
It would be useful if this project supported the `AWS_SHARED_CREDENTIALS_FILE` and `AWS_CONFIG_FILE` environment variables, allowing for custom locations of credentials and config files to be used.

The environment variables are documented [here](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html).

I personally prefer to keep my aws dotfiles in the `~/.config/aws/` directory.

**Comment by mcohen01** [comment]
i think you can set env var `AWS_CREDENTIAL_PROFILES_FILE` to point at your custom aws config file

**Comment by ChrisLane** [comment]
Thanks for giving a solution!
