### ISSUE TITLE
S3 Select support

### ISSUE THREAD

**Issue by irinarenteria** [mcohen01/amazonica#410]
Hi,

I'm trying to use the [select object content](https://docs.aws.amazon.com/AmazonS3/latest/dev/SelectObjectContentUsingJava.html) functionality in S3 and it doesn't seem to be available in amazonica. I thought that this would be "automatically" included since amazonica uses reflection?

Thank you!

**Comment by mcohen01** [comment]
`(s3/select-object-content :bucket-name "foo" :key "bar")`

**Comment by irinarenteria** [comment]
<img width="698" alt="Screen Shot 2019-04-17 at 9 05 40 AM" src="https://user-images.githubusercontent.com/12979335/56294179-23c45e00-60f0-11e9-9e0b-e8d0f7c7b0a4.png">

 It doesn't seem to be in the list of functions and I'm getting a `CompilerException java.lang.RuntimeException: No such var: aws-s3/select-object-content` when calling it.

**Comment by mcohen01** [comment]
are you running the latest version? i also see you don't have `restore-object-v2` in your list, just from a glance.

**Comment by irinarenteria** [comment]
The project I'm working with has amazonica pinned to `0.3.112` and `lein deps :tree` shows dependencies that use amazonica are pulling in the same version. I tried upgrading to the latest version, but I consistently get this when running `lein uberjar`:

<img width="1035" alt="Screen Shot 2019-04-17 at 12 12 53 PM" src="https://user-images.githubusercontent.com/12979335/56307336-406d8f80-610a-11e9-89ad-19fe08977fb7.png">

It seems like there might still be an issue with dependencies being out of sync. The relevant part of `project.clj` looks like this:

```clojure
                 [com.amazonaws/aws-lambda-java-core "1.2.0"]
                 [com.amazonaws/aws-lambda-java-events "1.2.0"
                 :exclusions [com.amazonaws/aws-java-sdk-kinesis
                              com.amazonaws/aws-java-sdk-dynamodb
                              com.amazonaws/aws-java-sdk-s3
                              joda-time
                              com.amazonaws/aws-java-sdk-sns
                              com.amazonaws/aws-java-sdk-cognitoidentity]]
                 [amazonica "0.3.22"
                  :exclusions [com.amazonaws/aws-java-sdk
                               com.amazonaws/amazon-kinesis-client]]
                 [com.amazonaws/aws-java-sdk-s3 "1.9.33"]
                 [com.amazonaws/aws-java-sdk-sns "1.9.33"]
                 [com.amazonaws/aws-java-sdk-sqs "1.9.33"]
                 [com.amazonaws/aws-java-sdk-simpledb "1.9.33"]
                 [com.amazonaws/aws-java-sdk-lambda "1.9.33"]
                 [com.amazonaws/aws-java-sdk-iam "1.9.33"]
                 [com.amazonaws/aws-java-sdk-logs "1.9.33"]
```

**Comment by irinarenteria** [comment]
Pulling in ` [com.amazonaws/aws-java-sdk-cloudsearch "1.11.535"]` fixed that issue. Seeing a new problem though. I can't seem to import `amazonica.aws.cloudwatchevents`. I've added this to the dependencies:

```clojure
[com.amazonaws/aws-java-sdk-cloudwatch "1.11.535"]
[com.amazonaws/aws-java-sdk-events "1.11.535"]
```
and getting: `Caused by: java.io.FileNotFoundException: Could not locate amazonica/aws/cloudwatchevents__init.class or amazonica/aws/cloudwatchevents.clj on classpath.`

I see the cloudwatchevents module on master, but when I downloaded the `0.3.22` release zip, I only see `cloudwatch` in there:

<img width="577" alt="Screen Shot 2019-04-17 at 1 06 29 PM" src="https://user-images.githubusercontent.com/12979335/56310523-b7f2ed00-6111-11e9-8e5c-bc8795b7fbce.png">

**Comment by mcohen01** [comment]
Right, you can manually specify the AWS Java SDK to latest version in your `project.clj` but if you're pinned to some older version of amazonica you're not going to be able to use some service for which there is no clj file.

**Comment by irinarenteria** [comment]
Ah, I see what happened now. I was only looking at the releases tab in GitHub and thought `0.3.22` was the latest version. Thought I entered the twilight zone there for a moment when we were talking about `0.3.112` being the "old" version and `0.3.22` being the "new" version. I checked clojars for the newest version and that fixes the issue. Thank you for your help, @mcohen01!
