### ISSUE TITLE
Marshalling records from DynamoDB streams

### ISSUE THREAD

**Issue by lordgankoo** [mcohen01/amazonica#425]
What would be the best way to take records from Dynamo DB stream events and marshall them into Clojure data (the same as is done for records taken directly out of DDB)? Since they're JSON formatted in this context, I haven't been able to figure out how to put them through the usual amazonica marshalling logic, but it would seem to make sense to leverage that same logic if possible.

**Comment by mcohen01** [comment]
not sure i understand. marshalling in amazonica is between clojure data <> java objects. you have json. why can't you just convert the json to clojure data? (sorry, i haven't done much with dynamo recently so i'm probably missing the context re stream events.)

**Comment by lordgankoo** [comment]
Yeah, sorry, probably didn't word the original question correctly. I guess what I'm really trying to ask is whether this particular conversion is even properly within the scope of amazonica. Or in other words, whether it should be possible to seamlessly pull events, and the records they contain, from a DynamoDB stream straight into clojure data. It still involves converting those records out of Dynamo's "typed" format (e.g. `"key": {"type": value}`), which is where I was trying to see if there was some logic reuse that could be done. It's just that the source data is JSON rather than Java objects.

**Comment by mcohen01** [comment]
if you're talking about the `event-source` field on a `Record` then yeah, i think you're gonna have to handle that manually

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_Record.html

https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/dynamodbv2/model/Record.html

**Comment by lordgankoo** [comment]
No, what I'm ultimately after are `NewImage` and `OldImage` - these are located under `Record->dynamodb`. The type of both of those is `String to AttributeValue object map`.


[https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamRecord.html](https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_streams_StreamRecord.html)

**Comment by lordgankoo** [comment]
Come to think of it, my use case (if it helps) is a stream processor which will watch for changes in Dynamo via Dynamo's change stream, and push the new/changed/deleted records to ElasticSearch in that streaming manner. I suppose since this is ultimately going to end up as a lambda request handler, it's not really in the scope of what amazonica does after all... but let me know if you think otherwise.
