### ISSUE TITLE
Unable to set user-defined metadata

### ISSUE THREAD

**Issue by umairaslamm** [mcohen01/amazonica#429]
I am trying to attach some user-defined metadata to my s3 put call.

https://docs.aws.amazon.com/AmazonS3/latest/user-guide/add-object-metadata.html#add-object-metadata-user-defined

Here's the code for the put-object form.

```
(s3/put-object
                 cred
                 :bucket-name bucket-name
                 :key key
                 :metadata {:item_doi "item doi val"}
                 :file file)
```

I do not see the item_doi key value pair in the object properties Metadata section

**Comment by mcohen01** [comment]
i think you need the [`user-metadata`](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/s3/model/ObjectMetadata.html#setUserMetadata-java.util.Map-) key as well:

```
(s3/put-object
                 cred
                 :bucket-name bucket-name
                 :key key
                 :metadata {
                   :user-metadata {:item_doi "item doi val"}}
                 :file file)
```

**Comment by umairaslamm** [comment]
:metadata {:user-metadata {:item_doi "item doi val"}} worked.
Thanks a lot. It would be helpful if there is one example of user-metadata in https://github.com/mcohen01/amazonica#s3
