### ISSUE TITLE
acm namespace under certificatemanager.clj causes import to fail

### ISSUE THREAD

**Issue by pfarwick-latacora** [mcohen01/amazonica#433]
Hello,
Currently getting the error:
`Could not locate amazonica/aws/acm__init.class, amazonica/aws/acm.clj or amazonica/aws/acm.cljc on classpath.` when trying to import the acm namespace. 

I did a bit of digging as to why this was. 

It appears that the namespace used to be certificatemanager but was changed to acm here: https://github.com/mcohen01/amazonica/commit/89d913795cb7600a7f79838d5f99c2e26194f6d8#diff-e557faeddc6a312496d3d467c178ddf9

The issue is the file name was not changed from certificatemanager.clj to acm.clj so now the import fails. 

Thanks!

**Comment by mcohen01** [comment]
fixed by https://github.com/mcohen01/amazonica/pull/434
