### ISSUE TITLE
Unaccurate :arglists for #'amazonica.aws.simpleemail/send-email

### ISSUE THREAD

**Issue by vemv** [mcohen01/amazonica#441]
`#'amazonica.aws.simpleemail/send-email` can accept e.g. 7 arguments, but its :arglists object doesn't suggest so:

```clj
user> (-> #'amazonica.aws.simpleemail/send-email meta :arglists)
([send-email-request])
```

This confuses tooling like Eastwood, which is unfortunate is it prevents one from using it as a hard check in CI.

Would appreciate an improvement!

Thanks - V

**Comment by vemv** [comment]
...when I say `e.g. 7 arguments` I'm refering to the keyword arguments.

So maybe the right arglist would be `([& {keys [...] :as send-email-request}])`?

**Comment by mcohen01** [comment]
The whole library is based on reflection. Most functions are generated at runtime. This library's never going to offer a good experience with tools that rely on introspection. Pull requests welcome though! 😄 

Please read the readme. The [JavaDocs](https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/simpleemail/model/SendEmailRequest.html) will be helpful. The invocation will look something like

`(send-email
  :destination {:to-addresses ["someone@hotmail.com"]}
  :message {:subject "hi" :body "hello there"}
  :return-path "some_url")

**Comment by vemv** [comment]
Hey there! Thanks for the reply.

> The whole library is based on reflection. Most functions are generated at runtime. This library's never going to offer a good experience with tools that rely on introspection.

Not sure if this assessment is correct. Eastwood works via `tools.analyzer`, which is analog to a real `eval`. So, provided that the arglists are factually correct, Eastwood will be happy with them!

I think it boils down to adding a `&` in the right place. One can note that `([send-email-request])` simply isn't correct - a human can also note how this function accepts kwargs, yet it lacks a `&`.

> Pull requests welcome though!

I tried out some hacks recently which I'd like to contribute at some point, you might find them interesting.

Meanwhile the `&` addition should be pretty simple to accomplish. I cannot immediately contribute it though (as I have to get permission at work first) but for the time being I'd really appreciate if you could fix it.
