### ISSUE TITLE
Class Not Found Exception

### ISSUE THREAD

**Issue by caryfitzhugh** [mcohen01/amazonica#85]
java.lang.ClassNotFoundException: com.amazonaws.auth.profile.ProfileCredentialsProvider

I am trying to use amazonica but get this failure when I require any amazonica.aws.\* package.

Does anyone have ideas?

**Comment by kubek2k** [comment]
@alilee the cheshire is added to classpath implicitly - my way to go was to explicitly add repl deplendencies as stated here:
http://docs.lighttable.com/#connect-to-an-nrepl-server?

but, I've added exclusion for jackson: 

```clojure
(defproject amazonica-test "0.1.0-SNAPSHOT"
  :description "FIXME: write description"
  :url "http://example.com/FIXME"
  :license {:name "Eclipse Public License"
            :url "http://www.eclipse.org/legal/epl-v10.html"}
  :dependencies [[org.clojure/clojure "1.6.0"]
                 [lein-light-nrepl "0.1.0" :exclusions [[com.fasterxml.jackson.core/jackson-core]]]
                 [amazonica "0.3.19"]]
  :repl-options {:nrepl-middleware [lighttable.nrepl.handler/lighttable-ops]})
```
